In [32]:
import pandas as pd
import numpy as np

In [77]:
df_reliable = pd.read_pickle("../processed/df_reliable.pkl")

print(df_reliable.shape)
print(df_reliable["report_date"].min())
print(df_reliable["report_date"].max())

(1650419, 28)
2021-01-01 00:00:00
2026-09-13 00:00:00

In [78]:
df_reliable

,market_name,commodity_name,report_date,state_id,state_name,market_id,commodity_id,total_arrivals,arrivals,unit_of_arrivals,...,day_of_week,week_of_year,days_since_last_report,price_lag_1,price_lag_2,price_lag_3,price_lag_7,price_roll_mean_7,price_roll_std_7,price_roll_mean_30
12237,APMC Aatpadi,Pomegranate,2021-01-14,20,Maharashtra,1901,160,14.0,14.0,Metric Tonnes,...,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12238,APMC Aatpadi,Pomegranate,2021-01-15,20,Maharashtra,1901,160,10.0,10.0,Metric Tonnes,...,4,2,1.0,13500.0,NaN,NaN,NaN,NaN,NaN,NaN
12239,APMC Aatpadi,Pomegranate,2021-01-17,20,Maharashtra,1901,160,24.0,24.0,Metric Tonnes,...,6,2,2.0,13500.0,13500.0,NaN,NaN,NaN,NaN,NaN
12240,APMC Aatpadi,Pomegranate,2021-01-18,20,Maharashtra,1901,160,18.0,18.0,Metric Tonnes,...,0,3,1.0,15000.0,13500.0,13500.0,NaN,14000.000000,866.025404,NaN
12241,APMC Aatpadi,Pomegranate,2021-01-19,20,Maharashtra,1901,160,22.0,22.0,Metric Tonnes,...,1,3,1.0,12000.0,15000.0,13500.0,NaN,13500.000000,1224.744871,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703482,Washim(Ansing),Wheat,2026-08-27,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,3,35,2.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2428.333333
1703483,Washim(Ansing),Wheat,2026-08-31,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,0,36,4.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2431.666667
1703485,Washim(Ansing),Wheat,2026-09-03,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,3,36,3.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2438.333333
1703486,Washim(Ansing),Wheat,2026-09-04,20,Maharashtra,2162,1,4.0,1.5,Metric Tonnes,...,4,36,1.0,2400.0,2450.0,2450.0,2450.0,2442.857143,18.898224,2440.000000
1703488,Washim(Ansing),Wheat,2026-09-07,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,0,37,3.0,2500.0,2400.0,2450.0,2450.0,2450.000000,28.867513,2445.000000

In [95]:
DAILY_KEYS = [
    "market_name",
    "commodity_name",
    "report_date"
]

df_daily = (
    df_reliable
    .groupby(DAILY_KEYS, as_index=False)
    .agg(
        modal_price=("modal_price", "median"),
        min_price=("min_price", "median"),
        max_price=("max_price", "median"),
        arrivals=("arrivals", "sum"),
        variety_count=("variety", "nunique"),
        grade_count=("grade", "nunique")
    )
)

df_daily = (
    df_daily
    .sort_values(DAILY_KEYS)
    .reset_index(drop=True)
)

print("Original rows:", len(df_reliable))
print("Daily rows:", len(df_daily))
print("Date range:", df_daily["report_date"].min(), "→", df_daily["report_date"].max())

Original rows: 1650419
Daily rows: 1615735
Date range: 2021-01-01 00:00:00 → 2026-09-13 00:00:00

In [96]:
df_reliable

,market_name,commodity_name,report_date,state_id,state_name,market_id,commodity_id,total_arrivals,arrivals,unit_of_arrivals,...,price_lag_1,price_lag_2,price_lag_3,price_lag_7,price_roll_mean_7,price_roll_std_7,price_roll_mean_30,target_price,target_date,horizon_days
0,APMC Aatpadi,Pomegranate,2021-01-14,20,Maharashtra,1901,160,14.0,14.0,Metric Tonnes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10500.0,2021-01-22,8.0
1,APMC Aatpadi,Pomegranate,2021-01-15,20,Maharashtra,1901,160,10.0,10.0,Metric Tonnes,...,13500.0,NaN,NaN,NaN,NaN,NaN,NaN,12500.0,2021-01-24,9.0
2,APMC Aatpadi,Pomegranate,2021-01-17,20,Maharashtra,1901,160,24.0,24.0,Metric Tonnes,...,13500.0,13500.0,NaN,NaN,NaN,NaN,NaN,15000.0,2021-01-26,9.0
3,APMC Aatpadi,Pomegranate,2021-01-18,20,Maharashtra,1901,160,18.0,18.0,Metric Tonnes,...,15000.0,13500.0,13500.0,NaN,14000.000000,866.025404,NaN,18500.0,2021-02-04,17.0
4,APMC Aatpadi,Pomegranate,2021-01-19,20,Maharashtra,1901,160,22.0,22.0,Metric Tonnes,...,12000.0,15000.0,13500.0,NaN,13500.000000,1224.744871,NaN,18500.0,2021-02-12,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650414,Washim(Ansing),Wheat,2026-08-27,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2428.333333,NaN,NaT,NaN
1650415,Washim(Ansing),Wheat,2026-08-31,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2431.666667,NaN,NaT,NaN
1650416,Washim(Ansing),Wheat,2026-09-03,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2438.333333,NaN,NaT,NaN
1650417,Washim(Ansing),Wheat,2026-09-04,20,Maharashtra,2162,1,4.0,1.5,Metric Tonnes,...,2400.0,2450.0,2450.0,2450.0,2442.857143,18.898224,2440.000000,NaN,NaT,NaN
1650418,Washim(Ansing),Wheat,2026-09-07,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,2500.0,2400.0,2450.0,2450.0,2450.000000,28.867513,2445.000000,NaN,NaT,NaN

In [97]:
GROUP_KEYS = [
    "market_name",
    "commodity_name"
]

grp = df_daily.groupby(GROUP_KEYS)["modal_price"]

# Calendar features
df_daily["year"] = df_daily["report_date"].dt.year
df_daily["month"] = df_daily["report_date"].dt.month
df_daily["day_of_week"] = df_daily["report_date"].dt.dayofweek
df_daily["week_of_year"] = (
    df_daily["report_date"].dt.isocalendar().week.astype(int)
)

# Gap since previous observation
df_daily["days_since_last_report"] = (
    df_daily
    .groupby(GROUP_KEYS)["report_date"]
    .diff()
    .dt.days
)

# Price lags
df_daily["price_lag_1"] = grp.shift(1)
df_daily["price_lag_2"] = grp.shift(2)
df_daily["price_lag_3"] = grp.shift(3)
df_daily["price_lag_7"] = grp.shift(7)

# Rolling features — use shift(1) to avoid leakage
df_daily["price_roll_mean_7"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(7, min_periods=3).mean()
    )
)

df_daily["price_roll_std_7"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(7, min_periods=3).std()
    )
)

df_daily["price_roll_mean_30"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(30, min_periods=5).mean()
    )
)

print("Shape:", df_daily.shape)

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "modal_price",
            "price_lag_1",
            "price_lag_7",
            "price_roll_mean_7",
            "price_roll_std_7",
            "price_roll_mean_30"
        ]
    ].head(15)
)

Shape: (1615735, 21)
     market_name commodity_name report_date  modal_price  price_lag_1  \
0   APMC Aatpadi    Pomegranate  2021-01-14      13500.0          NaN
1   APMC Aatpadi    Pomegranate  2021-01-15      13500.0      13500.0
2   APMC Aatpadi    Pomegranate  2021-01-17      15000.0      13500.0
3   APMC Aatpadi    Pomegranate  2021-01-18      12000.0      15000.0
4   APMC Aatpadi    Pomegranate  2021-01-19      12500.0      12000.0
5   APMC Aatpadi    Pomegranate  2021-01-20      13500.0      12500.0
6   APMC Aatpadi    Pomegranate  2021-01-21      13500.0      13500.0
7   APMC Aatpadi    Pomegranate  2021-01-22      10500.0      13500.0
8   APMC Aatpadi    Pomegranate  2021-01-24      12500.0      10500.0
9   APMC Aatpadi    Pomegranate  2021-01-26      15000.0      12500.0
10  APMC Aatpadi    Pomegranate  2021-02-04      18500.0      15000.0
11  APMC Aatpadi    Pomegranate  2021-02-12      18500.0      18500.0
12  APMC Aatpadi    Pomegranate  2021-02-15      18500.0      18500.0
13  APMC Aatpadi    Pomegranate  2021-02-19      16500.0      18500.0
14  APMC Aatpadi    Pomegranate  2021-02-22      18500.0      16500.0

    price_lag_7  price_roll_mean_7  price_roll_std_7  price_roll_mean_30
0           NaN                NaN               NaN                 NaN
1           NaN                NaN               NaN                 NaN
2           NaN                NaN               NaN                 NaN
3           NaN       14000.000000        866.025404                 NaN
4           NaN       13500.000000       1224.744871                 NaN
5           NaN       13300.000000       1151.086443        13300.000000
6           NaN       13333.333333       1032.795559        13333.333333
7       13500.0       13357.142857        944.911183        13357.142857
8       13500.0       12928.571429       1426.784597        13000.000000
9       15000.0       12785.714286       1409.998311        12944.444444
10      12000.0       12785.714286       1409.998311        13150.000000
11      12500.0       13714.285714       2514.245130        13636.363636
12      13500.0       14571.428571       3005.946488        14041.666667
13      13500.0       15285.714286       3289.593983        14384.615385
14      10500.0       15714.285714       3212.698021        14535.714286

In [98]:
# 7th future observation for the same market + commodity

df_daily["target_price"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .shift(-7)
)

df_daily["target_date"] = (
    df_daily
    .groupby(GROUP_KEYS)["report_date"]
    .shift(-7)
)

df_daily["horizon_days"] = (
    df_daily["target_date"]
    - df_daily["report_date"]
).dt.days

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "modal_price",
            "target_price",
            "target_date",
            "horizon_days"
        ]
    ].head(15)
)

     market_name commodity_name report_date  modal_price  target_price  \
0   APMC Aatpadi    Pomegranate  2021-01-14      13500.0       10500.0
1   APMC Aatpadi    Pomegranate  2021-01-15      13500.0       12500.0
2   APMC Aatpadi    Pomegranate  2021-01-17      15000.0       15000.0
3   APMC Aatpadi    Pomegranate  2021-01-18      12000.0       18500.0
4   APMC Aatpadi    Pomegranate  2021-01-19      12500.0       18500.0
5   APMC Aatpadi    Pomegranate  2021-01-20      13500.0       18500.0
6   APMC Aatpadi    Pomegranate  2021-01-21      13500.0       16500.0
7   APMC Aatpadi    Pomegranate  2021-01-22      10500.0       18500.0
8   APMC Aatpadi    Pomegranate  2021-01-24      12500.0       13500.0
9   APMC Aatpadi    Pomegranate  2021-01-26      15000.0       13500.0
10  APMC Aatpadi    Pomegranate  2021-02-04      18500.0       11500.0
11  APMC Aatpadi    Pomegranate  2021-02-12      18500.0       13500.0
12  APMC Aatpadi    Pomegranate  2021-02-15      18500.0       13500.0
13  APMC Aatpadi    Pomegranate  2021-02-19      16500.0       17200.0
14  APMC Aatpadi    Pomegranate  2021-02-22      18500.0       13500.0

   target_date  horizon_days
0   2021-01-22           8.0
1   2021-01-24           9.0
2   2021-01-26           9.0
3   2021-02-04          17.0
4   2021-02-12          24.0
5   2021-02-15          26.0
6   2021-02-19          29.0
7   2021-02-22          31.0
8   2021-02-23          30.0
9   2021-02-24          29.0
10  2021-02-25          21.0
11  2021-02-26          14.0
12  2021-02-28          13.0
13  2021-03-01          10.0
14  2021-03-02           8.0

In [99]:
# Keep only forecasts where the 7th future observation
# occurs 7 to 14 calendar days later.

df_model = df_daily[
    df_daily["horizon_days"].between(7, 14)
].copy()

# Remove rows where a future target does not exist
df_model = df_model.dropna(
    subset=["target_price"]
).copy()

print("Final modeling rows:", len(df_model))

print("\nHorizon distribution:")
print(
    df_model["horizon_days"]
    .value_counts()
    .sort_index()
)

print("\nDate range:")
print(
    df_model["report_date"].min(),
    "→",
    df_model["report_date"].max()
)

Final modeling rows: 1243583

Horizon distribution:
horizon_days
7.0      71703
8.0     350661
9.0     262336
10.0    177752
11.0    130972
12.0     99682
13.0     78950
14.0     71527
Name: count, dtype: int64

Date range:
2021-01-01 00:00:00 → 2026-09-06 00:00:00

In [100]:
# Percentage change from current price to the 7th future observation

df_model["pct_change_7"] = (
    (df_model["target_price"] - df_model["modal_price"])
    / df_model["modal_price"]
)

# Direction classes
df_model["direction"] = pd.cut(
    df_model["pct_change_7"],
    bins=[-np.inf, -0.02, 0.02, np.inf],
    labels=["down", "flat", "up"]
)

print("Direction counts:")
print(df_model["direction"].value_counts())

print("\nDirection percentages:")
print(
    (
        df_model["direction"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
)

Direction counts:
direction
up      451224
down    440096
flat    352263
Name: count, dtype: int64

Direction percentages:
direction
up      36.28
down    35.39
flat    28.33
Name: proportion, dtype: float64

In [102]:
FEATURES = [
    "market_name",
    "commodity_name",

    "modal_price",
    "min_price",
    "max_price",
    "arrivals",

    "days_since_last_report",

    "price_lag_1",
    "price_lag_2",
    "price_lag_3",
    "price_lag_7",

    "price_roll_mean_7",
    "price_roll_std_7",
    "price_roll_mean_30",

    "year",
    "month",
    "day_of_week",
    "week_of_year"
]

CATEGORICAL = [
    "market_name",
    "commodity_name"
]

print("Number of features:", len(FEATURES))
print("\nFeatures:")
for feature in FEATURES:
    print("-", feature)

Number of features: 18

Features:
- market_name
- commodity_name
- modal_price
- min_price
- max_price
- arrivals
- days_since_last_report
- price_lag_1
- price_lag_2
- price_lag_3
- price_lag_7
- price_roll_mean_7
- price_roll_std_7
- price_roll_mean_30
- year
- month
- day_of_week
- week_of_year

In [103]:
# Chronological split
# Train:      up to 2025-06-30
# Validation: 2025-07-01 to 2025-12-31
# Test:       2026-01-01 onward

split_train_end = pd.Timestamp("2025-06-30")
split_val_end = pd.Timestamp("2025-12-31")

train = df_model[
    df_model["report_date"] <= split_train_end
].copy()

val = df_model[
    (df_model["report_date"] > split_train_end) &
    (df_model["report_date"] <= split_val_end)
].copy()

test = df_model[
    df_model["report_date"] > split_val_end
].copy()

print("Train shape:", train.shape)
print("Validation shape:", val.shape)
print("Test shape:", test.shape)

print("\nDate ranges:")

print(
    "Train:",
    train["report_date"].min(),
    "→",
    train["report_date"].max()
)

print(
    "Validation:",
    val["report_date"].min(),
    "→",
    val["report_date"].max()
)

print(
    "Test:",
    test["report_date"].min(),
    "→",
    test["report_date"].max()
)

Train shape: (948244, 26)
Validation shape: (115363, 26)
Test shape: (179976, 26)

Date ranges:
Train: 2021-01-01 00:00:00 → 2025-06-30 00:00:00
Validation: 2025-07-01 00:00:00 → 2025-12-31 00:00:00
Test: 2026-01-01 00:00:00 → 2026-09-06 00:00:00

In [104]:
for col in CATEGORICAL:
    categories = df_model[col].astype("category").cat.categories

    train[col] = pd.Categorical(
        train[col],
        categories=categories
    )

    val[col] = pd.Categorical(
        val[col],
        categories=categories
    )

    test[col] = pd.Categorical(
        test[col],
        categories=categories
    )

print("Categorical columns prepared:")
print(CATEGORICAL)

print("\nTrain dtypes:")
print(train[CATEGORICAL].dtypes)

Categorical columns prepared:
['market_name', 'commodity_name']

Train dtypes:
market_name       category
commodity_name    category
dtype: object

In [105]:
df_reliable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650419 entries, 0 to 1650418
Data columns (total 31 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   market_name             1650419 non-null  object
 1   commodity_name          1650419 non-null  object
 2   report_date             1650419 non-null  datetime64[ns]
 3   state_id                1650419 non-null  int64
 4   state_name              1650419 non-null  object
 5   market_id               1650419 non-null  int64
 6   commodity_id            1650419 non-null  int64
 7   total_arrivals          1650419 non-null  float64
 8   arrivals                1650419 non-null  float64
 9   unit_of_arrivals        1650419 non-null  object
 10  variety                 1650419 non-null  object
 11  grade                   1650419 non-null  object
 12  min_price               1650419 non-null  float64
 13  max_price               1650419 non-null  float64
 14  modal_price             1650419 non-null  float64
 15  unit_of_price           1650419 non-null  object
 16  year                    1650419 non-null  int32
 17  month                   1650419 non-null  int32
 18  day_of_week             1650419 non-null  int32
 19  week_of_year            1650419 non-null  int64
 20  days_since_last_report  1646401 non-null  float64
 21  price_lag_1             1646401 non-null  float64
 22  price_lag_2             1642478 non-null  float64
 23  price_lag_3             1638607 non-null  float64
 24  price_lag_7             1623393 non-null  float64
 25  price_roll_mean_7       1638607 non-null  float64
 26  price_roll_std_7        1638607 non-null  float64
 27  price_roll_mean_30      1630962 non-null  float64
 28  target_price            1623393 non-null  float64
 29  target_date             1623393 non-null  datetime64[ns]
 30  horizon_days            1623393 non-null  float64
dtypes: datetime64[ns](2), float64(15), int32(3), int64(4), object(7)
memory usage: 371.5+ MB

In [106]:
X_train_reg = train[FEATURES]
X_val_reg = val[FEATURES]
X_test_reg = test[FEATURES]

y_train_reg = train["target_price"]
y_val_reg = val["target_price"]
y_test_reg = test["target_price"]

print("X_train:", X_train_reg.shape)
print("X_val:", X_val_reg.shape)
print("X_test:", X_test_reg.shape)

print("\ny_train:", y_train_reg.shape)
print("y_val:", y_val_reg.shape)
print("y_test:", y_test_reg.shape)

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [107]:
from lightgbm import LGBMRegressor, early_stopping, log_evaluation

regressor = LGBMRegressor(
    objective="regression",
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

regressor.fit(
    X_train_reg,
    np.log1p(y_train_reg),

    eval_set=[
        (X_val_reg, np.log1p(y_val_reg))
    ],

    eval_metric="l2",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.0560116
[200]	valid_0's l2: 0.0526517
[300]	valid_0's l2: 0.0526851
Early stopping, best iteration is:
[208]	valid_0's l2: 0.052601

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, min_data_in_leaf=100,
              n_estimators=3000, n_jobs=-1, num_leaves=63,
              objective='regression', random_state=42, subsample=0.8)

In [108]:
# Predict log(price), then convert back to the original price scale

pred_log = regressor.predict(
    X_test_reg
)

pred_price = np.expm1(pred_log)

# Prices cannot be negative
pred_price = np.maximum(pred_price, 0)

print("Number of predictions:", len(pred_price))
print("First 10 predictions:")
print(pred_price[:10])

Number of predictions: 179976
First 10 predictions:
[8581.50472643 8821.30416337 8287.74946423 8021.42440279 8502.87535812
 9029.4185256  9130.35801429 9155.4934576  9345.70931801 8952.60646852]

In [109]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(
    y_test_reg,
    pred_price
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_reg,
        pred_price
    )
)

smape = (
    100
    * np.mean(
        2 * np.abs(pred_price - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(pred_price)
            + 1e-8
        )
    )
)

print(f"MAE   : ₹{mae:,.2f}")
print(f"RMSE  : ₹{rmse:,.2f}")
print(f"sMAPE : {smape:.2f}%")

MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

In [111]:
# Naive forecast:
# assume the future price will be the current modal price

naive_pred = test["modal_price"].values

naive_mae = mean_absolute_error(
    y_test_reg,
    naive_pred
)

naive_rmse = np.sqrt(
    mean_squared_error(
        y_test_reg,
        naive_pred
    )
)

naive_smape = (
    100
    * np.mean(
        2 * np.abs(naive_pred - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(naive_pred)
            + 1e-8
        )
    )
)

print("NAIVE BASELINE")
print(f"MAE   : ₹{naive_mae:,.2f}")
print(f"RMSE  : ₹{naive_rmse:,.2f}")
print(f"sMAPE : {naive_smape:.2f}%")

print("\nLIGHTGBM")
print(f"MAE   : ₹{mae:,.2f}")
print(f"RMSE  : ₹{rmse:,.2f}")
print(f"sMAPE : {smape:.2f}%")

NAIVE BASELINE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

LIGHTGBM
MAE   : ₹471.35
RMSE  : ₹1,128.30
sMAPE : 13.12%

In [112]:
# Recalculate test predictions and metrics from scratch
# to make sure no variable was accidentally overwritten.

pred_log_check = regressor.predict(X_test_reg)
pred_price_check = np.maximum(np.expm1(pred_log_check), 0)

actual = y_test_reg.to_numpy()
naive_check = test["modal_price"].to_numpy()

# LightGBM
lgbm_mae_check = mean_absolute_error(actual, pred_price_check)
lgbm_rmse_check = np.sqrt(
    mean_squared_error(actual, pred_price_check)
)

lgbm_smape_check = (
    100
    * np.mean(
        2 * np.abs(pred_price_check - actual)
        / (np.abs(actual) + np.abs(pred_price_check) + 1e-8)
    )
)

# Naive
naive_mae_check = mean_absolute_error(actual, naive_check)
naive_rmse_check = np.sqrt(
    mean_squared_error(actual, naive_check)
)

naive_smape_check = (
    100
    * np.mean(
        2 * np.abs(naive_check - actual)
        / (np.abs(actual) + np.abs(naive_check) + 1e-8)
    )
)

print("LIGHTGBM")
print(f"MAE   : ₹{lgbm_mae_check:,.2f}")
print(f"RMSE  : ₹{lgbm_rmse_check:,.2f}")
print(f"sMAPE : {lgbm_smape_check:.2f}%")

print("\nNAIVE")
print(f"MAE   : ₹{naive_mae_check:,.2f}")
print(f"RMSE  : ₹{naive_rmse_check:,.2f}")
print(f"sMAPE : {naive_smape_check:.2f}%")

LIGHTGBM
MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

NAIVE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

classificstion

In [113]:
# Encode DOWN / FLAT / UP
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit(["down", "flat", "up"])

train["direction_encoded"] = label_encoder.transform(
    train["direction"]
)

val["direction_encoded"] = label_encoder.transform(
    val["direction"]
)

test["direction_encoded"] = label_encoder.transform(
    test["direction"]
)

print("Class mapping:")
print(
    dict(
        zip(
            label_encoder.classes_,
            range(len(label_encoder.classes_))
        )
    )
)

print("\nTrain class counts:")
print(train["direction"].value_counts())

Class mapping:
{np.str_('down'): 0, np.str_('flat'): 1, np.str_('up'): 2}

Train class counts:
direction
up      344926
down    335103
flat    268215
Name: count, dtype: int64

In [114]:
X_train_cls = train[FEATURES]
X_val_cls = val[FEATURES]
X_test_cls = test[FEATURES]

y_train_cls = train["direction_encoded"]
y_val_cls = val["direction_encoded"]
y_test_cls = test["direction_encoded"]

print("X_train:", X_train_cls.shape)
print("X_val:", X_val_cls.shape)
print("X_test:", X_test_cls.shape)

print("\ny_train:", y_train_cls.shape)
print("y_val:", y_val_cls.shape)
print("y_test:", y_test_cls.shape)

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [115]:
from lightgbm import LGBMClassifier, early_stopping, log_evaluation

classifier = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=3000,
    learning_rate=0.05,
    num_leaves=63,
    min_data_in_leaf=200,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

classifier.fit(
    X_train_cls,
    y_train_cls,

    eval_set=[
        (X_val_cls, y_val_cls)
    ],

    eval_metric="multi_logloss",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Training until validation scores don't improve for 100 rounds
[100]	valid_0's multi_logloss: 0.932924
[200]	valid_0's multi_logloss: 0.923701
[300]	valid_0's multi_logloss: 0.921615
[400]	valid_0's multi_logloss: 0.921848
Early stopping, best iteration is:
[323]	valid_0's multi_logloss: 0.921241

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, min_data_in_leaf=200,
               n_estimators=3000, n_jobs=-1, num_class=3, num_leaves=63,
               objective='multiclass', random_state=42, subsample=0.8)

In [116]:
# Predict class labels on the test set

pred_direction_encoded = (
    classifier
    .predict(X_test_cls)
    .astype(int)
    .ravel()
)

pred_direction = label_encoder.inverse_transform(
    pred_direction_encoded
)

print("Number of predictions:", len(pred_direction))

print("\nFirst 20 predictions:")
print(pred_direction[:20])

Number of predictions: 179976

First 20 predictions:
['down' 'down' 'up' 'up' 'up' 'down' 'up' 'up' 'up' 'up' 'up' 'down'
 'down' 'up' 'up' 'up' 'down' 'up' 'up' 'up']

In [117]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test_cls,
    pred_direction_encoded
)

print(f"Overall classification accuracy: {accuracy:.4f}")
print(f"Overall classification accuracy: {accuracy * 100:.2f}%")

Overall classification accuracy: 0.5494
Overall classification accuracy: 54.94%

In [118]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_cls,
        pred_direction_encoded,
        target_names=label_encoder.classes_,
        digits=4
    )
)

              precision    recall  f1-score   support

        down     0.5386    0.6082    0.5713     61894
        flat     0.5711    0.4424    0.4986     51835
          up     0.5476    0.5781    0.5624     66247

    accuracy                         0.5494    179976
   macro avg     0.5525    0.5429    0.5441    179976
weighted avg     0.5513    0.5494    0.5471    179976

In [119]:
# Accuracy only on meaningful movements:
# DOWN and UP, excluding FLAT

non_flat_mask = test["direction"] != "flat"

actual_non_flat = test.loc[
    non_flat_mask,
    "direction"
]

pred_non_flat = pd.Series(
    pred_direction,
    index=test.index
).loc[non_flat_mask]

non_flat_accuracy = (
    actual_non_flat.values == pred_non_flat.values
).mean()

print(
    f"UP/DOWN accuracy excluding FLAT: "
    f"{non_flat_accuracy * 100:.2f}%"
)

print(
    f"Non-flat test observations: "
    f"{len(actual_non_flat):,}"
)

UP/DOWN accuracy excluding FLAT: 59.26%
Non-flat test observations: 128,141

In [120]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test_cls,
    pred_direction_encoded
)

print("Rows = Actual")
print("Columns = Predicted")

print("\nLabels:", list(label_encoder.classes_))
print(cm)

Rows = Actual
Columns = Predicted

Labels: [np.str_('down'), np.str_('flat'), np.str_('up')]
[[37643  7168 17083]
 [14349 22931 14555]
 [17899 10050 38298]]

In [121]:
# Prediction probabilities for DOWN / FLAT / UP

probabilities = classifier.predict_proba(
    X_test_cls
)

print("Probability shape:", probabilities.shape)

print("\nFirst 5 probability rows:")
print(probabilities[:5])

print("\nClass order:")
print(label_encoder.classes_)

Probability shape: (179976, 3)

First 5 probability rows:
[[0.44953254 0.10197502 0.44849244]
 [0.48801903 0.10096031 0.41102066]
 [0.215994   0.10170511 0.68230089]
 [0.27722159 0.10537852 0.61739989]
 [0.43607928 0.08682986 0.47709086]]

Class order:
['down' 'flat' 'up']

In [122]:
# Create a clean test prediction table

results = test[
    [
        "report_date",
        "target_date",
        "market_name",
        "commodity_name",
        "modal_price",
        "target_price",
        "direction"
    ]
].copy()

# Regression prediction
results["predicted_price"] = pred_price

# Classification prediction
results["predicted_direction"] = pred_direction

# Probability of each class
results["prob_down"] = probabilities[:, 0]
results["prob_flat"] = probabilities[:, 1]
results["prob_up"] = probabilities[:, 2]

# Highest probability = model confidence
results["direction_confidence"] = probabilities.max(axis=1)

print(results.head(10))

    report_date target_date   market_name commodity_name  modal_price  \
792  2026-05-08  2026-05-21  APMC Aatpadi    Pomegranate       8500.0
793  2026-05-10  2026-05-22  APMC Aatpadi    Pomegranate       9000.0
794  2026-05-14  2026-05-25  APMC Aatpadi    Pomegranate       7200.0
802  2026-06-01  2026-06-14  APMC Aatpadi    Pomegranate       8000.0
803  2026-06-02  2026-06-15  APMC Aatpadi    Pomegranate       8700.0
804  2026-06-07  2026-06-17  APMC Aatpadi    Pomegranate      10500.0
805  2026-06-08  2026-06-21  APMC Aatpadi    Pomegranate       9000.0
806  2026-06-09  2026-06-23  APMC Aatpadi    Pomegranate       9000.0
807  2026-06-10  2026-06-24  APMC Aatpadi    Pomegranate       9200.0
808  2026-06-11  2026-06-25  APMC Aatpadi    Pomegranate       8200.0

     target_price direction  predicted_price predicted_direction  prob_down  \
792        7500.0      down      8581.504726                down   0.449533
793        9200.0        up      8821.304163                down   0.488019
794        7000.0      down      8287.749464                  up   0.215994
802        9000.0        up      8021.424403                  up   0.277222
803        8700.0      flat      8502.875358                  up   0.436079
804       10000.0      down      9029.418526                down   0.524655
805       11300.0        up      9130.358014                  up   0.400516
806       10000.0        up      9155.493458                  up   0.404441
807        9300.0      flat      9345.709318                  up   0.382294
808        8500.0        up      8952.606469                  up   0.266342

     prob_flat   prob_up  direction_confidence
792   0.101975  0.448492              0.449533
793   0.100960  0.411021              0.488019
794   0.101705  0.682301              0.682301
802   0.105379  0.617400              0.617400
803   0.086830  0.477091              0.477091
804   0.093031  0.382314              0.524655
805   0.091360  0.508124              0.508124
806   0.089410  0.506149              0.506149
807   0.095076  0.522630              0.522630
808   0.086999  0.646658              0.646658

In [123]:
# Expected percentage change according to the regression model

results["predicted_pct_change"] = (
    (
        results["predicted_price"]
        - results["modal_price"]
    )
    / results["modal_price"]
) * 100

print(
    results[
        [
            "commodity_name",
            "market_name",
            "report_date",
            "modal_price",
            "predicted_price",
            "predicted_pct_change",
            "predicted_direction",
            "direction_confidence"
        ]
    ].head(10)
)

    commodity_name   market_name report_date  modal_price  predicted_price  \
792    Pomegranate  APMC Aatpadi  2026-05-08       8500.0      8581.504726
793    Pomegranate  APMC Aatpadi  2026-05-10       9000.0      8821.304163
794    Pomegranate  APMC Aatpadi  2026-05-14       7200.0      8287.749464
802    Pomegranate  APMC Aatpadi  2026-06-01       8000.0      8021.424403
803    Pomegranate  APMC Aatpadi  2026-06-02       8700.0      8502.875358
804    Pomegranate  APMC Aatpadi  2026-06-07      10500.0      9029.418526
805    Pomegranate  APMC Aatpadi  2026-06-08       9000.0      9130.358014
806    Pomegranate  APMC Aatpadi  2026-06-09       9000.0      9155.493458
807    Pomegranate  APMC Aatpadi  2026-06-10       9200.0      9345.709318
808    Pomegranate  APMC Aatpadi  2026-06-11       8200.0      8952.606469

     predicted_pct_change predicted_direction  direction_confidence
792              0.958879                down              0.449533
793             -1.985509                down              0.488019
794             15.107631                  up              0.682301
802              0.267805                  up              0.617400
803             -2.265800                  up              0.477091
804            -14.005538                down              0.524655
805              1.448422                  up              0.508124
806              1.727705                  up              0.506149
807              1.583797                  up              0.522630
808              9.178128                  up              0.646658

In [124]:
def make_recommendation(row):

    if (
        row["predicted_direction"] == "up"
        and row["direction_confidence"] >= 0.60
    ):
        return "HOLD"

    elif (
        row["predicted_direction"] == "down"
        and row["direction_confidence"] >= 0.60
    ):
        return "SELL"

    else:
        return "NO STRONG SIGNAL"


results["recommendation"] = results.apply(
    make_recommendation,
    axis=1
)

print("Recommendation counts:")
print(results["recommendation"].value_counts())

print("\nExamples:")
print(
    results[
        [
            "commodity_name",
            "market_name",
            "modal_price",
            "predicted_price",
            "predicted_pct_change",
            "predicted_direction",
            "direction_confidence",
            "recommendation"
        ]
    ].head(20)
)

Recommendation counts:
recommendation
NO STRONG SIGNAL    133497
HOLD                 24582
SELL                 21897
Name: count, dtype: int64

Examples:
    commodity_name   market_name  modal_price  predicted_price  \
792    Pomegranate  APMC Aatpadi       8500.0      8581.504726
793    Pomegranate  APMC Aatpadi       9000.0      8821.304163
794    Pomegranate  APMC Aatpadi       7200.0      8287.749464
802    Pomegranate  APMC Aatpadi       8000.0      8021.424403
803    Pomegranate  APMC Aatpadi       8700.0      8502.875358
804    Pomegranate  APMC Aatpadi      10500.0      9029.418526
805    Pomegranate  APMC Aatpadi       9000.0      9130.358014
806    Pomegranate  APMC Aatpadi       9000.0      9155.493458
807    Pomegranate  APMC Aatpadi       9200.0      9345.709318
808    Pomegranate  APMC Aatpadi       8200.0      8952.606469
809    Pomegranate  APMC Aatpadi       9000.0      9057.004531
811    Pomegranate  APMC Aatpadi      10000.0      9543.900073
812    Pomegranate  APMC Aatpadi      11300.0     10126.790441
813    Pomegranate  APMC Aatpadi      10000.0     10184.936563
814    Pomegranate  APMC Aatpadi       9300.0      9890.813701
815    Pomegranate  APMC Aatpadi       8500.0      9268.325216
816    Pomegranate  APMC Aatpadi      10500.0      9692.267472
817    Pomegranate  APMC Aatpadi       9500.0      9640.406740
818    Pomegranate  APMC Aatpadi       9500.0      9746.862337
819    Pomegranate  APMC Aatpadi       9500.0      9608.288710

     predicted_pct_change predicted_direction  direction_confidence  \
792              0.958879                down              0.449533
793             -1.985509                down              0.488019
794             15.107631                  up              0.682301
802              0.267805                  up              0.617400
803             -2.265800                  up              0.477091
804            -14.005538                down              0.524655
805              1.448422                  up              0.508124
806              1.727705                  up              0.506149
807              1.583797                  up              0.522630
808              9.178128                  up              0.646658
809              0.633384                  up              0.505108
811             -4.560999                down              0.510391
812            -10.382385                down              0.619763
813              1.849366                  up              0.464577
814              6.352835                  up              0.658942
815              9.039120                  up              0.685049
816             -7.692691                down              0.519893
817              1.477966                  up              0.504979
818              2.598551                  up              0.536471
819              1.139881                  up              0.525281

       recommendation
792  NO STRONG SIGNAL
793  NO STRONG SIGNAL
794              HOLD
802              HOLD
803  NO STRONG SIGNAL
804  NO STRONG SIGNAL
805  NO STRONG SIGNAL
806  NO STRONG SIGNAL
807  NO STRONG SIGNAL
808              HOLD
809  NO STRONG SIGNAL
811  NO STRONG SIGNAL
812              SELL
813  NO STRONG SIGNAL
814              HOLD
815              HOLD
816  NO STRONG SIGNAL
817  NO STRONG SIGNAL
818  NO STRONG SIGNAL
819  NO STRONG SIGNAL

In [125]:
# Evaluate only the recommendations where the system
# actually made a decision.

decision_mask = results["recommendation"].isin(
    ["HOLD", "SELL"]
)

decision_results = results.loc[
    decision_mask
].copy()

# Actual direction
decision_results["correct_direction"] = (
    decision_results["predicted_direction"]
    == decision_results["direction"]
)

print("Total recommendations:", len(results))
print("HOLD/SELL decisions:", len(decision_results))

print("\nDirection accuracy on HOLD/SELL decisions:")
print(
    decision_results["correct_direction"].mean() * 100
)

print("\nAccuracy by recommendation:")
print(
    decision_results
    .groupby("recommendation")["correct_direction"]
    .mean()
    .mul(100)
)

Total recommendations: 179976
HOLD/SELL decisions: 46479

Direction accuracy on HOLD/SELL decisions:
68.69984293982229

Accuracy by recommendation:
recommendation
HOLD    68.289806
SELL    69.160159
Name: correct_direction, dtype: float64

In [126]:
# Check agreement between regression-implied movement
# and classification direction.

results["regression_direction"] = np.select(
    [
        results["predicted_pct_change"] < -2,
        results["predicted_pct_change"] > 2
    ],
    [
        "down",
        "up"
    ],
    default="flat"
)

results["models_agree"] = (
    results["regression_direction"]
    == results["predicted_direction"]
)

print("Model agreement:")
print(
    results["models_agree"].value_counts()
)

print("\nAgreement percentage:")
print(
    results["models_agree"].mean() * 100
)

Model agreement:
models_agree
True     130330
False     49646
Name: count, dtype: int64

Agreement percentage:
72.41521091701115

In [127]:
def make_strict_recommendation(row):

    if (
        row["predicted_direction"] == "up"
        and row["regression_direction"] == "up"
        and row["direction_confidence"] >= 0.60
    ):
        return "HOLD"

    elif (
        row["predicted_direction"] == "down"
        and row["regression_direction"] == "down"
        and row["direction_confidence"] >= 0.60
    ):
        return "SELL"

    else:
        return "NO STRONG SIGNAL"


results["strict_recommendation"] = results.apply(
    make_strict_recommendation,
    axis=1
)

print("Strict recommendation counts:")
print(
    results["strict_recommendation"].value_counts()
)

Strict recommendation counts:
strict_recommendation
NO STRONG SIGNAL    134532
HOLD                 24053
SELL                 21391
Name: count, dtype: int64

In [128]:
# Naive directional baseline:
# predict the future direction from the previous price movement.

naive_direction = np.where(
    test["modal_price"] > test["price_lag_1"],
    "up",
    np.where(
        test["modal_price"] < test["price_lag_1"],
        "down",
        "flat"
    )
)

naive_direction_accuracy = (
    naive_direction == test["direction"].astype(str).values
).mean()

print(
    f"Naive direction accuracy: "
    f"{naive_direction_accuracy * 100:.2f}%"
)

non_flat_mask_naive = (
    test["direction"].astype(str) != "flat"
)

naive_non_flat_accuracy = (
    naive_direction[non_flat_mask_naive]
    == test.loc[non_flat_mask_naive, "direction"].astype(str).values
).mean()

print(
    f"Naive UP/DOWN accuracy: "
    f"{naive_non_flat_accuracy * 100:.2f}%"
)

Naive direction accuracy: 32.05%
Naive UP/DOWN accuracy: 27.95%

In [129]:
# Direction performance by commodity on the test set

crop_results = []

for crop, group in test.groupby("commodity_name"):

    idx = group.index

    actual = group["direction"].astype(str).values
    predicted = pd.Series(
        pred_direction,
        index=test.index
    ).loc[idx].values

    overall_acc = (
        predicted == actual
    ).mean()

    non_flat = actual != "flat"

    if non_flat.sum() > 0:
        non_flat_acc = (
            predicted[non_flat] == actual[non_flat]
        ).mean()
    else:
        non_flat_acc = np.nan

    crop_results.append({
        "commodity": crop,
        "test_rows": len(group),
        "overall_accuracy": overall_acc,
        "up_down_accuracy": non_flat_acc
    })

per_crop_accuracy = (
    pd.DataFrame(crop_results)
    .sort_values(
        "up_down_accuracy",
        ascending=False
    )
)

print(per_crop_accuracy.head(20))

C:\Users\hp\AppData\Local\Temp\ipykernel_16960\880725385.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for crop, group in test.groupby("commodity_name"):
C:\Users\hp\AppData\Local\Temp\ipykernel_16960\880725385.py:17: RuntimeWarning: Mean of empty slice.
  ).mean()
c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\numpy\_core\_methods.py:144: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

                  commodity  test_rows  overall_accuracy  up_down_accuracy
75    Pointed gourd(Parval)        302          0.576159          0.764444
34                Drumstick       2585          0.605803          0.756286
60          Mango(Raw-Ripe)        963          0.603323          0.738462
74                     Plum         59          0.525424          0.738095
71           Pear(Marasebu)        168          0.607143          0.728571
88                 Seetapal        217          0.594470          0.724719
8                  Beetroot       1560          0.602564          0.708955
59                    Mango        784          0.588010          0.708006
6            Banana - Green        177          0.519774          0.707692
96             Sweet Potato        429          0.557110          0.705329
72                 Peas Wet       1482          0.572200          0.702748
100                  Tomato       6541          0.574683          0.698541
85         Ridgeguard(Tori)       3295          0.569651          0.697473
23              Cauliflower       5742          0.569488          0.696774
7                     Beans       2383          0.580361          0.694626
67              Onion Green       1391          0.552840          0.692669
36   French Beans(Frasbean)        284          0.626761          0.689922
57     Little gourd(Kundru)       1052          0.581749          0.689576
48                     Guar       4208          0.551331          0.688323
18                  Cabbage       5823          0.582689          0.688002

In [131]:
# Evaluate HOLD/SELL recommendations against baselines
# using the original test dataframe for price_lag_1.

issued_mask = results["recommendation"].isin(
    ["HOLD", "SELL"]
)

issued = results.loc[issued_mask].copy()

# Map recommendation to predicted direction
issued["predicted_action_direction"] = issued[
    "recommendation"
].map({
    "HOLD": "up",
    "SELL": "down"
})

# Actual direction
issued["actual_direction"] = issued["direction"].astype(str)

# -----------------------------
# 1. Model accuracy
# -----------------------------

model_action_accuracy = (
    issued["predicted_action_direction"]
    == issued["actual_direction"]
).mean()

# -----------------------------
# 2. Majority-class baseline
# -----------------------------

actual_counts = issued["actual_direction"].value_counts()

majority_direction = actual_counts.index[0]

majority_accuracy = (
    issued["actual_direction"]
    == majority_direction
).mean()

# -----------------------------
# 3. Naive previous-price baseline
# -----------------------------

# Get price_lag_1 from the original test dataframe
issued_lag1 = test.loc[issued.index, "price_lag_1"]

naive_action_direction = np.where(
    issued["modal_price"].values > issued_lag1.values,
    "up",
    np.where(
        issued["modal_price"].values < issued_lag1.values,
        "down",
        "flat"
    )
)

naive_accuracy = (
    naive_action_direction
    == issued["actual_direction"].values
).mean()

# -----------------------------
# Results
# -----------------------------

print("Issued HOLD/SELL decisions:", len(issued))

print("\nActual direction distribution:")
print(actual_counts)

print("\nMODEL")
print(f"Accuracy: {model_action_accuracy * 100:.2f}%")

print("\nMAJORITY BASELINE")
print(
    f"Always predict '{majority_direction}': "
    f"{majority_accuracy * 100:.2f}%"
)

print("\nNAIVE PREVIOUS-PRICE BASELINE")
print(
    f"Accuracy: {naive_accuracy * 100:.2f}%"
)

Issued HOLD/SELL decisions: 46479

Actual direction distribution:
actual_direction
up      20612
down    19426
flat     6441
Name: count, dtype: int64

MODEL
Accuracy: 68.70%

MAJORITY BASELINE
Always predict 'up': 44.35%

NAIVE PREVIOUS-PRICE BASELINE
Accuracy: 22.83%

evaluating regression model

In [132]:
# Regression performance by commodity
# Compare LightGBM against the naive current-price baseline.

reg_test = test[
    [
        "commodity_name",
        "target_price",
        "modal_price"
    ]
].copy()

reg_test["predicted_price"] = pred_price

reg_test["abs_error_model"] = (
    reg_test["target_price"]
    - reg_test["predicted_price"]
).abs()

reg_test["abs_error_naive"] = (
    reg_test["target_price"]
    - reg_test["modal_price"]
).abs()

crop_regression = (
    reg_test
    .groupby("commodity_name", observed=True)
    .agg(
        test_rows=("target_price", "size"),
        model_mae=("abs_error_model", "mean"),
        naive_mae=("abs_error_naive", "mean")
    )
    .reset_index()
)

crop_regression["mae_lift"] = (
    crop_regression["naive_mae"]
    - crop_regression["model_mae"]
)

crop_regression["mae_lift_pct"] = (
    crop_regression["mae_lift"]
    / crop_regression["naive_mae"]
) * 100

crop_regression = crop_regression.sort_values(
    "test_rows",
    ascending=False
)

print(crop_regression.head(20))

                commodity_name  test_rows   model_mae   naive_mae   mae_lift  \
102                      Wheat       9105   85.296022   92.921582   7.625560
65                       Onion       8481  226.462648  236.125044   9.662397
10    Bengal Gram(Gram)(Whole)       7098  209.623556  225.688574  16.065018
91                    Soyabean       6851  357.502907  344.318786 -13.184121
82   Red gram/Arhar/Tur(whole)       6769  312.329279  321.653494   9.324214
99                      Tomato       6541  307.622165  357.886256  50.264091
11       Bhindi(Ladies Finger)       6127  502.032140  571.800555  69.768415
17                     Brinjal       6092  432.844314  463.825181  30.980866
41                Green Chilli       6014  640.596786  700.526605  59.929818
18                     Cabbage       5823  187.213147  212.337455  25.124308
23                 Cauliflower       5742  334.796899  374.945315  40.148416
32            Cucumbar(Kheera)       5660  347.682820  381.571731  33.888911
12                Bitter gourd       4696  531.100013  607.629685  76.529672
76                      Potato       4676  108.339618   95.662318 -12.677300
51              Jowar(Sorghum)       4489  264.137387  291.468144  27.330758
47                        Guar       4208  861.796550  935.934886  74.138336
39               Ginger(Green)       3907  981.015775  979.602764  -1.413011
26             Chilly Capsicum       3800  525.293117  596.429211  71.136094
16                Bottle gourd       3795  302.243741  334.233992  31.990251
20                      Carrot       3644  270.025220  298.702525  28.677305

     mae_lift_pct
102      8.206446
65       4.092068
10       7.118224
91      -3.829045
82       2.898838
99      14.044711
11      12.201530
17       6.679427
41       8.554967
18      11.832255
23      10.707806
32       8.881400
12      12.594788
76     -13.252135
51       9.376928
47       7.921313
39      -0.144243
26      11.926997
16       9.571214
20       9.600624

In [134]:
priority_crops = [
    "Onion",
    "Tomato",
    "Soyabean",
    "Wheat",
    "Red gram/Arhar/Tur(whole)",
    "Cotton"
]

priority_regression = crop_regression[
    crop_regression["commodity_name"].isin(priority_crops)
].copy()

priority_regression = priority_regression.sort_values(
    "mae_lift_pct",
    ascending=False
)

print(priority_regression.to_string(index=False))

           commodity_name  test_rows  model_mae  naive_mae   mae_lift  mae_lift_pct
                   Tomato       6541 307.622165 357.886256  50.264091     14.044711
                    Wheat       9105  85.296022  92.921582   7.625560      8.206446
                    Onion       8481 226.462648 236.125044   9.662397      4.092068
Red gram/Arhar/Tur(whole)       6769 312.329279 321.653494   9.324214      2.898838
                 Soyabean       6851 357.502907 344.318786 -13.184121     -3.829045
                   Cotton       1420 234.299430 204.342444 -29.956986    -14.660188

In [135]:
priority_direction = per_crop_accuracy[
    per_crop_accuracy["commodity"].isin(priority_crops)
].copy()

priority_direction = priority_direction.sort_values(
    "up_down_accuracy",
    ascending=False
)

print(
    priority_direction.to_string(index=False)
)

                commodity  test_rows  overall_accuracy  up_down_accuracy
                   Tomato       6541          0.574683          0.698541
                    Onion       8481          0.562552          0.655294
                    Wheat       9105          0.528281          0.402926
                 Soyabean       6851          0.362429          0.337627
Red gram/Arhar/Tur(whole)       6769          0.401536          0.307445
                   Cotton       1420          0.542958          0.012422

In [136]:
# Compare actual and predicted direction distributions
# for the SIH priority crops.

priority_check = []

for crop in priority_crops:

    mask = test["commodity_name"] == crop

    actual = test.loc[mask, "direction"].astype(str)

    predicted = pd.Series(
        pred_direction,
        index=test.index
    ).loc[mask]

    priority_check.append({
        "commodity": crop,
        "n_test": len(actual),

        "actual_down_pct": (
            (actual == "down").mean() * 100
        ),

        "actual_flat_pct": (
            (actual == "flat").mean() * 100
        ),

        "actual_up_pct": (
            (actual == "up").mean() * 100
        ),

        "pred_down_pct": (
            (predicted == "down").mean() * 100
        ),

        "pred_flat_pct": (
            (predicted == "flat").mean() * 100
        ),

        "pred_up_pct": (
            (predicted == "up").mean() * 100
        )
    })

priority_check = pd.DataFrame(priority_check)

print(
    priority_check.to_string(index=False)
)

                commodity  n_test  actual_down_pct  actual_flat_pct  actual_up_pct  pred_down_pct  pred_flat_pct  pred_up_pct
                    Onion    8481        32.731989        16.707935      50.560075      44.063200       3.478363    52.458437
                   Tomato    6541        41.752026        20.379147      37.868827      49.977068       3.776181    46.246751
                 Soyabean    6851        33.571741        25.207999      41.220260      59.436579      38.052839     2.510582
                    Wheat    9105        24.986271        41.449753      33.563976      15.881384      57.353103    26.765513
Red gram/Arhar/Tur(whole)    6769        27.153198        40.271827      32.574974      48.515290      47.274339     4.210371
                   Cotton    1420        17.957746        54.647887      27.394366       1.267606      98.028169     0.704225

In [137]:
# Check how each priority crop is distributed in the TRAINING data.

train_crop_distribution = []

for crop in priority_crops:

    subset = train[
        train["commodity_name"] == crop
    ]

    counts = (
        subset["direction"]
        .astype(str)
        .value_counts()
    )

    total = len(subset)

    train_crop_distribution.append({
        "commodity": crop,
        "train_rows": total,

        "down_pct": (
            counts.get("down", 0) / total * 100
            if total > 0 else np.nan
        ),

        "flat_pct": (
            counts.get("flat", 0) / total * 100
            if total > 0 else np.nan
        ),

        "up_pct": (
            counts.get("up", 0) / total * 100
            if total > 0 else np.nan
        )
    })

train_crop_distribution = pd.DataFrame(
    train_crop_distribution
)

print(
    train_crop_distribution.to_string(index=False)
)

                commodity  train_rows  down_pct  flat_pct    up_pct
                    Onion       43334 42.276273 15.237458 42.486269
                   Tomato       39036 41.064658 16.725587 42.209755
                 Soyabean       52955 28.237183 44.579360 27.183458
                    Wheat       51596 28.304520 39.210404 32.485076
Red gram/Arhar/Tur(whole)       32022 26.335020 40.325401 33.339579
                   Cotton       12085 20.215143 57.550683 22.234175

In [138]:
# Check average prediction probabilities and confidence
# for each priority crop.

confidence_results = []

for crop in priority_crops:

    mask = test["commodity_name"] == crop

    if mask.sum() == 0:
        continue

    probs_crop = probabilities[mask.values]

    confidence_results.append({
        "commodity": crop,
        "test_rows": mask.sum(),

        "avg_prob_down": probs_crop[:, 0].mean(),
        "avg_prob_flat": probs_crop[:, 1].mean(),
        "avg_prob_up": probs_crop[:, 2].mean(),

        "avg_confidence": probs_crop.max(axis=1).mean()
    })

confidence_results = pd.DataFrame(
    confidence_results
)

print(
    confidence_results.to_string(index=False)
)

                commodity  test_rows  avg_prob_down  avg_prob_flat  avg_prob_up  avg_confidence
                    Onion       8481       0.392785       0.173502     0.433713        0.543000
                   Tomato       6541       0.416639       0.182679     0.400682        0.534353
                 Soyabean       6851       0.452913       0.394036     0.153051        0.520914
                    Wheat       9105       0.249467       0.443582     0.306951        0.538714
Red gram/Arhar/Tur(whole)       6769       0.404097       0.393474     0.202430        0.488620
                   Cotton       1420       0.183998       0.674011     0.141992        0.676632

In [139]:
importance = pd.DataFrame({
    "feature": FEATURES,
    "importance": classifier.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

print(importance.to_string(index=False))

               feature  importance
           market_name       16701
        commodity_name       11987
           modal_price        6708
          week_of_year        6379
                  year        2672
    price_roll_mean_30        1960
     price_roll_mean_7        1874
             max_price        1868
                 month        1684
      price_roll_std_7        1610
           price_lag_1        1585
             min_price        1529
           price_lag_2        1037
              arrivals         855
           price_lag_3         745
           price_lag_7         723
           day_of_week          93
days_since_last_report          68