In [1]:
import pandas as pd
import numpy as np

In [2]:
df_reliable = pd.read_pickle("../processed/df_reliable.pkl")

print(df_reliable.shape)
print(df_reliable["report_date"].min())
print(df_reliable["report_date"].max())

(1650419, 28)
2021-01-01 00:00:00
2026-09-13 00:00:00

In [3]:
df_reliable

,market_name,commodity_name,report_date,state_id,state_name,market_id,commodity_id,total_arrivals,arrivals,unit_of_arrivals,...,day_of_week,week_of_year,days_since_last_report,price_lag_1,price_lag_2,price_lag_3,price_lag_7,price_roll_mean_7,price_roll_std_7,price_roll_mean_30
12237,APMC Aatpadi,Pomegranate,2021-01-14,20,Maharashtra,1901,160,14.0,14.0,Metric Tonnes,...,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12238,APMC Aatpadi,Pomegranate,2021-01-15,20,Maharashtra,1901,160,10.0,10.0,Metric Tonnes,...,4,2,1.0,13500.0,NaN,NaN,NaN,NaN,NaN,NaN
12239,APMC Aatpadi,Pomegranate,2021-01-17,20,Maharashtra,1901,160,24.0,24.0,Metric Tonnes,...,6,2,2.0,13500.0,13500.0,NaN,NaN,NaN,NaN,NaN
12240,APMC Aatpadi,Pomegranate,2021-01-18,20,Maharashtra,1901,160,18.0,18.0,Metric Tonnes,...,0,3,1.0,15000.0,13500.0,13500.0,NaN,14000.000000,866.025404,NaN
12241,APMC Aatpadi,Pomegranate,2021-01-19,20,Maharashtra,1901,160,22.0,22.0,Metric Tonnes,...,1,3,1.0,12000.0,15000.0,13500.0,NaN,13500.000000,1224.744871,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703482,Washim(Ansing),Wheat,2026-08-27,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,3,35,2.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2428.333333
1703483,Washim(Ansing),Wheat,2026-08-31,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,0,36,4.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2431.666667
1703485,Washim(Ansing),Wheat,2026-09-03,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,3,36,3.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2438.333333
1703486,Washim(Ansing),Wheat,2026-09-04,20,Maharashtra,2162,1,4.0,1.5,Metric Tonnes,...,4,36,1.0,2400.0,2450.0,2450.0,2450.0,2442.857143,18.898224,2440.000000
1703488,Washim(Ansing),Wheat,2026-09-07,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,0,37,3.0,2500.0,2400.0,2450.0,2450.0,2450.000000,28.867513,2445.000000

In [4]:
DAILY_KEYS = [
    "market_name",
    "commodity_name",
    "report_date"
]

df_daily = (
    df_reliable
    .groupby(DAILY_KEYS, as_index=False)
    .agg(
        modal_price=("modal_price", "median"),
        min_price=("min_price", "median"),
        max_price=("max_price", "median"),
        arrivals=("arrivals", "sum"),
        variety_count=("variety", "nunique"),
        grade_count=("grade", "nunique")
    )
)

df_daily = (
    df_daily
    .sort_values(DAILY_KEYS)
    .reset_index(drop=True)
)

print("Original rows:", len(df_reliable))
print("Daily rows:", len(df_daily))
print("Date range:", df_daily["report_date"].min(), "→", df_daily["report_date"].max())

Original rows: 1650419
Daily rows: 1615735
Date range: 2021-01-01 00:00:00 → 2026-09-13 00:00:00

In [5]:
df_reliable

,market_name,commodity_name,report_date,state_id,state_name,market_id,commodity_id,total_arrivals,arrivals,unit_of_arrivals,...,day_of_week,week_of_year,days_since_last_report,price_lag_1,price_lag_2,price_lag_3,price_lag_7,price_roll_mean_7,price_roll_std_7,price_roll_mean_30
12237,APMC Aatpadi,Pomegranate,2021-01-14,20,Maharashtra,1901,160,14.0,14.0,Metric Tonnes,...,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12238,APMC Aatpadi,Pomegranate,2021-01-15,20,Maharashtra,1901,160,10.0,10.0,Metric Tonnes,...,4,2,1.0,13500.0,NaN,NaN,NaN,NaN,NaN,NaN
12239,APMC Aatpadi,Pomegranate,2021-01-17,20,Maharashtra,1901,160,24.0,24.0,Metric Tonnes,...,6,2,2.0,13500.0,13500.0,NaN,NaN,NaN,NaN,NaN
12240,APMC Aatpadi,Pomegranate,2021-01-18,20,Maharashtra,1901,160,18.0,18.0,Metric Tonnes,...,0,3,1.0,15000.0,13500.0,13500.0,NaN,14000.000000,866.025404,NaN
12241,APMC Aatpadi,Pomegranate,2021-01-19,20,Maharashtra,1901,160,22.0,22.0,Metric Tonnes,...,1,3,1.0,12000.0,15000.0,13500.0,NaN,13500.000000,1224.744871,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703482,Washim(Ansing),Wheat,2026-08-27,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,3,35,2.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2428.333333
1703483,Washim(Ansing),Wheat,2026-08-31,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,0,36,4.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2431.666667
1703485,Washim(Ansing),Wheat,2026-09-03,20,Maharashtra,2162,1,1.5,1.5,Metric Tonnes,...,3,36,3.0,2450.0,2450.0,2450.0,2450.0,2450.000000,0.000000,2438.333333
1703486,Washim(Ansing),Wheat,2026-09-04,20,Maharashtra,2162,1,4.0,1.5,Metric Tonnes,...,4,36,1.0,2400.0,2450.0,2450.0,2450.0,2442.857143,18.898224,2440.000000
1703488,Washim(Ansing),Wheat,2026-09-07,20,Maharashtra,2162,1,6.0,6.0,Metric Tonnes,...,0,37,3.0,2500.0,2400.0,2450.0,2450.0,2450.000000,28.867513,2445.000000

In [6]:
GROUP_KEYS = [
    "market_name",
    "commodity_name"
]

grp = df_daily.groupby(GROUP_KEYS)["modal_price"]

# Calendar features
df_daily["year"] = df_daily["report_date"].dt.year
df_daily["month"] = df_daily["report_date"].dt.month
df_daily["day_of_week"] = df_daily["report_date"].dt.dayofweek
df_daily["week_of_year"] = (
    df_daily["report_date"].dt.isocalendar().week.astype(int)
)

# Gap since previous observation
df_daily["days_since_last_report"] = (
    df_daily
    .groupby(GROUP_KEYS)["report_date"]
    .diff()
    .dt.days
)

# Price lags
df_daily["price_lag_1"] = grp.shift(1)
df_daily["price_lag_2"] = grp.shift(2)
df_daily["price_lag_3"] = grp.shift(3)
df_daily["price_lag_7"] = grp.shift(7)

# Rolling features — use shift(1) to avoid leakage
df_daily["price_roll_mean_7"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(7, min_periods=3).mean()
    )
)

df_daily["price_roll_std_7"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(7, min_periods=3).std()
    )
)

df_daily["price_roll_mean_30"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .transform(
        lambda s: s.shift(1).rolling(30, min_periods=5).mean()
    )
)

print("Shape:", df_daily.shape)

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "modal_price",
            "price_lag_1",
            "price_lag_7",
            "price_roll_mean_7",
            "price_roll_std_7",
            "price_roll_mean_30"
        ]
    ].head(15)
)

Shape: (1615735, 21)
     market_name commodity_name report_date  modal_price  price_lag_1  \
0   APMC Aatpadi    Pomegranate  2021-01-14      13500.0          NaN
1   APMC Aatpadi    Pomegranate  2021-01-15      13500.0      13500.0
2   APMC Aatpadi    Pomegranate  2021-01-17      15000.0      13500.0
3   APMC Aatpadi    Pomegranate  2021-01-18      12000.0      15000.0
4   APMC Aatpadi    Pomegranate  2021-01-19      12500.0      12000.0
5   APMC Aatpadi    Pomegranate  2021-01-20      13500.0      12500.0
6   APMC Aatpadi    Pomegranate  2021-01-21      13500.0      13500.0
7   APMC Aatpadi    Pomegranate  2021-01-22      10500.0      13500.0
8   APMC Aatpadi    Pomegranate  2021-01-24      12500.0      10500.0
9   APMC Aatpadi    Pomegranate  2021-01-26      15000.0      12500.0
10  APMC Aatpadi    Pomegranate  2021-02-04      18500.0      15000.0
11  APMC Aatpadi    Pomegranate  2021-02-12      18500.0      18500.0
12  APMC Aatpadi    Pomegranate  2021-02-15      18500.0      18500.0
13  APMC Aatpadi    Pomegranate  2021-02-19      16500.0      18500.0
14  APMC Aatpadi    Pomegranate  2021-02-22      18500.0      16500.0

    price_lag_7  price_roll_mean_7  price_roll_std_7  price_roll_mean_30
0           NaN                NaN               NaN                 NaN
1           NaN                NaN               NaN                 NaN
2           NaN                NaN               NaN                 NaN
3           NaN       14000.000000        866.025404                 NaN
4           NaN       13500.000000       1224.744871                 NaN
5           NaN       13300.000000       1151.086443        13300.000000
6           NaN       13333.333333       1032.795559        13333.333333
7       13500.0       13357.142857        944.911183        13357.142857
8       13500.0       12928.571429       1426.784597        13000.000000
9       15000.0       12785.714286       1409.998311        12944.444444
10      12000.0       12785.714286       1409.998311        13150.000000
11      12500.0       13714.285714       2514.245130        13636.363636
12      13500.0       14571.428571       3005.946488        14041.666667
13      13500.0       15285.714286       3289.593983        14384.615385
14      10500.0       15714.285714       3212.698021        14535.714286

In [7]:
# 7th future observation for the same market + commodity

df_daily["target_price"] = (
    df_daily
    .groupby(GROUP_KEYS)["modal_price"]
    .shift(-7)
)

df_daily["target_date"] = (
    df_daily
    .groupby(GROUP_KEYS)["report_date"]
    .shift(-7)
)

df_daily["horizon_days"] = (
    df_daily["target_date"]
    - df_daily["report_date"]
).dt.days

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "modal_price",
            "target_price",
            "target_date",
            "horizon_days"
        ]
    ].head(15)
)

     market_name commodity_name report_date  modal_price  target_price  \
0   APMC Aatpadi    Pomegranate  2021-01-14      13500.0       10500.0
1   APMC Aatpadi    Pomegranate  2021-01-15      13500.0       12500.0
2   APMC Aatpadi    Pomegranate  2021-01-17      15000.0       15000.0
3   APMC Aatpadi    Pomegranate  2021-01-18      12000.0       18500.0
4   APMC Aatpadi    Pomegranate  2021-01-19      12500.0       18500.0
5   APMC Aatpadi    Pomegranate  2021-01-20      13500.0       18500.0
6   APMC Aatpadi    Pomegranate  2021-01-21      13500.0       16500.0
7   APMC Aatpadi    Pomegranate  2021-01-22      10500.0       18500.0
8   APMC Aatpadi    Pomegranate  2021-01-24      12500.0       13500.0
9   APMC Aatpadi    Pomegranate  2021-01-26      15000.0       13500.0
10  APMC Aatpadi    Pomegranate  2021-02-04      18500.0       11500.0
11  APMC Aatpadi    Pomegranate  2021-02-12      18500.0       13500.0
12  APMC Aatpadi    Pomegranate  2021-02-15      18500.0       13500.0
13  APMC Aatpadi    Pomegranate  2021-02-19      16500.0       17200.0
14  APMC Aatpadi    Pomegranate  2021-02-22      18500.0       13500.0

   target_date  horizon_days
0   2021-01-22           8.0
1   2021-01-24           9.0
2   2021-01-26           9.0
3   2021-02-04          17.0
4   2021-02-12          24.0
5   2021-02-15          26.0
6   2021-02-19          29.0
7   2021-02-22          31.0
8   2021-02-23          30.0
9   2021-02-24          29.0
10  2021-02-25          21.0
11  2021-02-26          14.0
12  2021-02-28          13.0
13  2021-03-01          10.0
14  2021-03-02           8.0

In [8]:
# Keep only forecasts where the 7th future observation
# occurs 7 to 14 calendar days later.

df_model = df_daily[
    df_daily["horizon_days"].between(7, 14)
].copy()

# Remove rows where a future target does not exist
df_model = df_model.dropna(
    subset=["target_price"]
).copy()

print("Final modeling rows:", len(df_model))

print("\nHorizon distribution:")
print(
    df_model["horizon_days"]
    .value_counts()
    .sort_index()
)

print("\nDate range:")
print(
    df_model["report_date"].min(),
    "→",
    df_model["report_date"].max()
)

Final modeling rows: 1243583

Horizon distribution:
horizon_days
7.0      71703
8.0     350661
9.0     262336
10.0    177752
11.0    130972
12.0     99682
13.0     78950
14.0     71527
Name: count, dtype: int64

Date range:
2021-01-01 00:00:00 → 2026-09-06 00:00:00

In [9]:
# Percentage change from current price to the 7th future observation

df_model["pct_change_7"] = (
    (df_model["target_price"] - df_model["modal_price"])
    / df_model["modal_price"]
)

# Direction classes
df_model["direction"] = pd.cut(
    df_model["pct_change_7"],
    bins=[-np.inf, -0.02, 0.02, np.inf],
    labels=["down", "flat", "up"]
)

print("Direction counts:")
print(df_model["direction"].value_counts())

print("\nDirection percentages:")
print(
    (
        df_model["direction"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
)

Direction counts:
direction
up      451224
down    440096
flat    352263
Name: count, dtype: int64

Direction percentages:
direction
up      36.28
down    35.39
flat    28.33
Name: proportion, dtype: float64

In [10]:
FEATURES = [
    "market_name",
    "commodity_name",

    "modal_price",
    "min_price",
    "max_price",
    "arrivals",

    "days_since_last_report",

    "price_lag_1",
    "price_lag_2",
    "price_lag_3",
    "price_lag_7",

    "price_roll_mean_7",
    "price_roll_std_7",
    "price_roll_mean_30",

    "year",
    "month",
    "day_of_week",
    "week_of_year"
]

CATEGORICAL = [
    "market_name",
    "commodity_name"
]

print("Number of features:", len(FEATURES))
print("\nFeatures:")
for feature in FEATURES:
    print("-", feature)

Number of features: 18

Features:
- market_name
- commodity_name
- modal_price
- min_price
- max_price
- arrivals
- days_since_last_report
- price_lag_1
- price_lag_2
- price_lag_3
- price_lag_7
- price_roll_mean_7
- price_roll_std_7
- price_roll_mean_30
- year
- month
- day_of_week
- week_of_year

In [11]:
# Chronological split
# Train:      up to 2025-06-30
# Validation: 2025-07-01 to 2025-12-31
# Test:       2026-01-01 onward

split_train_end = pd.Timestamp("2025-06-30")
split_val_end = pd.Timestamp("2025-12-31")

train = df_model[
    df_model["report_date"] <= split_train_end
].copy()

val = df_model[
    (df_model["report_date"] > split_train_end) &
    (df_model["report_date"] <= split_val_end)
].copy()

test = df_model[
    df_model["report_date"] > split_val_end
].copy()

print("Train shape:", train.shape)
print("Validation shape:", val.shape)
print("Test shape:", test.shape)

print("\nDate ranges:")

print(
    "Train:",
    train["report_date"].min(),
    "→",
    train["report_date"].max()
)

print(
    "Validation:",
    val["report_date"].min(),
    "→",
    val["report_date"].max()
)

print(
    "Test:",
    test["report_date"].min(),
    "→",
    test["report_date"].max()
)

Train shape: (948244, 26)
Validation shape: (115363, 26)
Test shape: (179976, 26)

Date ranges:
Train: 2021-01-01 00:00:00 → 2025-06-30 00:00:00
Validation: 2025-07-01 00:00:00 → 2025-12-31 00:00:00
Test: 2026-01-01 00:00:00 → 2026-09-06 00:00:00

In [12]:
for col in CATEGORICAL:
    categories = df_model[col].astype("category").cat.categories

    train[col] = pd.Categorical(
        train[col],
        categories=categories
    )

    val[col] = pd.Categorical(
        val[col],
        categories=categories
    )

    test[col] = pd.Categorical(
        test[col],
        categories=categories
    )

print("Categorical columns prepared:")
print(CATEGORICAL)

print("\nTrain dtypes:")
print(train[CATEGORICAL].dtypes)

Categorical columns prepared:
['market_name', 'commodity_name']

Train dtypes:
market_name       category
commodity_name    category
dtype: object

In [13]:
df_reliable.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1650419 entries, 12237 to 1703488
Data columns (total 28 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   market_name             1650419 non-null  object
 1   commodity_name          1650419 non-null  object
 2   report_date             1650419 non-null  datetime64[ns]
 3   state_id                1650419 non-null  int64
 4   state_name              1650419 non-null  object
 5   market_id               1650419 non-null  int64
 6   commodity_id            1650419 non-null  int64
 7   total_arrivals          1650419 non-null  float64
 8   arrivals                1650419 non-null  float64
 9   unit_of_arrivals        1650419 non-null  object
 10  variety                 1650419 non-null  object
 11  grade                   1650419 non-null  object
 12  min_price               1650419 non-null  float64
 13  max_price               1650419 non-null  float64
 14  modal_price             1650419 non-null  float64
 15  unit_of_price           1650419 non-null  object
 16  year                    1650419 non-null  int32
 17  month                   1650419 non-null  int32
 18  day_of_week             1650419 non-null  int32
 19  week_of_year            1650419 non-null  int64
 20  days_since_last_report  1646401 non-null  float64
 21  price_lag_1             1646401 non-null  float64
 22  price_lag_2             1642478 non-null  float64
 23  price_lag_3             1638607 non-null  float64
 24  price_lag_7             1623393 non-null  float64
 25  price_roll_mean_7       1638607 non-null  float64
 26  price_roll_std_7        1638607 non-null  float64
 27  price_roll_mean_30      1630962 non-null  float64
dtypes: datetime64[ns](1), float64(13), int32(3), int64(4), object(7)
memory usage: 346.3+ MB

In [14]:
X_train_reg = train[FEATURES]
X_val_reg = val[FEATURES]
X_test_reg = test[FEATURES]

y_train_reg = train["target_price"]
y_val_reg = val["target_price"]
y_test_reg = test["target_price"]

print("X_train:", X_train_reg.shape)
print("X_val:", X_val_reg.shape)
print("X_test:", X_test_reg.shape)

print("\ny_train:", y_train_reg.shape)
print("y_val:", y_val_reg.shape)
print("y_test:", y_test_reg.shape)

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [15]:
from lightgbm import LGBMRegressor, early_stopping, log_evaluation

regressor = LGBMRegressor(
    objective="regression",
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

regressor.fit(
    X_train_reg,
    np.log1p(y_train_reg),

    eval_set=[
        (X_val_reg, np.log1p(y_val_reg))
    ],

    eval_metric="l2",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012080 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3316
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 18
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Start training from score 7.723530
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.0560116
[200]	valid_0's l2: 0.0526517
[300]	valid_0's l2: 0.0526851
Early stopping, best iteration is:
[208]	valid_0's l2: 0.052601

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, min_data_in_leaf=100,
              n_estimators=3000, n_jobs=-1, num_leaves=63,
              objective='regression', random_state=42, subsample=0.8)

In [16]:
# Predict log(price), then convert back to the original price scale

pred_log = regressor.predict(
    X_test_reg
)

pred_price = np.expm1(pred_log)

# Prices cannot be negative
pred_price = np.maximum(pred_price, 0)

print("Number of predictions:", len(pred_price))
print("First 10 predictions:")
print(pred_price[:10])

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
Number of predictions: 179976
First 10 predictions:
[8581.50472643 8821.30416337 8287.74946423 8021.42440279 8502.87535812
 9029.4185256  9130.35801429 9155.4934576  9345.70931801 8952.60646852]

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(
    y_test_reg,
    pred_price
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_reg,
        pred_price
    )
)

smape = (
    100
    * np.mean(
        2 * np.abs(pred_price - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(pred_price)
            + 1e-8
        )
    )
)

print(f"MAE   : ₹{mae:,.2f}")
print(f"RMSE  : ₹{rmse:,.2f}")
print(f"sMAPE : {smape:.2f}%")

MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

In [18]:
# Naive forecast:
# assume the future price will be the current modal price

naive_pred = test["modal_price"].values

naive_mae = mean_absolute_error(
    y_test_reg,
    naive_pred
)

naive_rmse = np.sqrt(
    mean_squared_error(
        y_test_reg,
        naive_pred
    )
)

naive_smape = (
    100
    * np.mean(
        2 * np.abs(naive_pred - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(naive_pred)
            + 1e-8
        )
    )
)

print("NAIVE BASELINE")
print(f"MAE   : ₹{naive_mae:,.2f}")
print(f"RMSE  : ₹{naive_rmse:,.2f}")
print(f"sMAPE : {naive_smape:.2f}%")

print("\nLIGHTGBM")
print(f"MAE   : ₹{mae:,.2f}")
print(f"RMSE  : ₹{rmse:,.2f}")
print(f"sMAPE : {smape:.2f}%")

NAIVE BASELINE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

LIGHTGBM
MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

In [19]:
# Recalculate test predictions and metrics from scratch
# to make sure no variable was accidentally overwritten.

pred_log_check = regressor.predict(X_test_reg)
pred_price_check = np.maximum(np.expm1(pred_log_check), 0)

actual = y_test_reg.to_numpy()
naive_check = test["modal_price"].to_numpy()

# LightGBM
lgbm_mae_check = mean_absolute_error(actual, pred_price_check)
lgbm_rmse_check = np.sqrt(
    mean_squared_error(actual, pred_price_check)
)

lgbm_smape_check = (
    100
    * np.mean(
        2 * np.abs(pred_price_check - actual)
        / (np.abs(actual) + np.abs(pred_price_check) + 1e-8)
    )
)

# Naive
naive_mae_check = mean_absolute_error(actual, naive_check)
naive_rmse_check = np.sqrt(
    mean_squared_error(actual, naive_check)
)

naive_smape_check = (
    100
    * np.mean(
        2 * np.abs(naive_check - actual)
        / (np.abs(actual) + np.abs(naive_check) + 1e-8)
    )
)

print("LIGHTGBM")
print(f"MAE   : ₹{lgbm_mae_check:,.2f}")
print(f"RMSE  : ₹{lgbm_rmse_check:,.2f}")
print(f"sMAPE : {lgbm_smape_check:.2f}%")

print("\nNAIVE")
print(f"MAE   : ₹{naive_mae_check:,.2f}")
print(f"RMSE  : ₹{naive_rmse_check:,.2f}")
print(f"sMAPE : {naive_smape_check:.2f}%")

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
LIGHTGBM
MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

NAIVE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

classificstion

In [20]:
# Encode DOWN / FLAT / UP
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit(["down", "flat", "up"])

train["direction_encoded"] = label_encoder.transform(
    train["direction"]
)

val["direction_encoded"] = label_encoder.transform(
    val["direction"]
)

test["direction_encoded"] = label_encoder.transform(
    test["direction"]
)

print("Class mapping:")
print(
    dict(
        zip(
            label_encoder.classes_,
            range(len(label_encoder.classes_))
        )
    )
)

print("\nTrain class counts:")
print(train["direction"].value_counts())

Class mapping:
{np.str_('down'): 0, np.str_('flat'): 1, np.str_('up'): 2}

Train class counts:
direction
up      344926
down    335103
flat    268215
Name: count, dtype: int64

In [21]:
X_train_cls = train[FEATURES]
X_val_cls = val[FEATURES]
X_test_cls = test[FEATURES]

y_train_cls = train["direction_encoded"]
y_val_cls = val["direction_encoded"]
y_test_cls = test["direction_encoded"]

print("X_train:", X_train_cls.shape)
print("X_val:", X_val_cls.shape)
print("X_test:", X_test_cls.shape)

print("\ny_train:", y_train_cls.shape)
print("y_val:", y_val_cls.shape)
print("y_test:", y_test_cls.shape)

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [22]:
from lightgbm import LGBMClassifier, early_stopping, log_evaluation

classifier = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=3000,
    learning_rate=0.05,
    num_leaves=63,
    min_data_in_leaf=200,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

classifier.fit(
    X_train_cls,
    y_train_cls,

    eval_set=[
        (X_val_cls, y_val_cls)
    ],

    eval_metric="multi_logloss",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.053195 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3316
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 18
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Start training from score -1.040174
[LightGBM] [Info] Start training from score -1.262823
[LightGBM] [Info] Start training from score -1.011282
Training until validation scores don't improve for 100 rounds
[100]	valid_0's multi_logloss: 0.932924
[200]	valid_0's multi_logloss: 0.923701
[300]	valid_0's multi_logloss: 0.921615
[400]	valid_0's multi_logloss: 0.921848
Early stopping, best iteration is:
[323]	valid_0's multi_logloss: 0.921241

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, min_data_in_leaf=200,
               n_estimators=3000, n_jobs=-1, num_class=3, num_leaves=63,
               objective='multiclass', random_state=42, subsample=0.8)

In [23]:
# Predict class labels on the test set

pred_direction_encoded = (
    classifier
    .predict(X_test_cls)
    .astype(int)
    .ravel()
)

pred_direction = label_encoder.inverse_transform(
    pred_direction_encoded
)

print("Number of predictions:", len(pred_direction))

print("\nFirst 20 predictions:")
print(pred_direction[:20])

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
Number of predictions: 179976

First 20 predictions:
['down' 'down' 'up' 'up' 'up' 'down' 'up' 'up' 'up' 'up' 'up' 'down'
 'down' 'up' 'up' 'up' 'down' 'up' 'up' 'up']

In [24]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test_cls,
    pred_direction_encoded
)

print(f"Overall classification accuracy: {accuracy:.4f}")
print(f"Overall classification accuracy: {accuracy * 100:.2f}%")

Overall classification accuracy: 0.5494
Overall classification accuracy: 54.94%

In [25]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_cls,
        pred_direction_encoded,
        target_names=label_encoder.classes_,
        digits=4
    )
)

              precision    recall  f1-score   support

        down     0.5386    0.6082    0.5713     61894
        flat     0.5711    0.4424    0.4986     51835
          up     0.5476    0.5781    0.5624     66247

    accuracy                         0.5494    179976
   macro avg     0.5525    0.5429    0.5441    179976
weighted avg     0.5513    0.5494    0.5471    179976

In [26]:
# Accuracy only on meaningful movements:
# DOWN and UP, excluding FLAT

non_flat_mask = test["direction"] != "flat"

actual_non_flat = test.loc[
    non_flat_mask,
    "direction"
]

pred_non_flat = pd.Series(
    pred_direction,
    index=test.index
).loc[non_flat_mask]

non_flat_accuracy = (
    actual_non_flat.values == pred_non_flat.values
).mean()

print(
    f"UP/DOWN accuracy excluding FLAT: "
    f"{non_flat_accuracy * 100:.2f}%"
)

print(
    f"Non-flat test observations: "
    f"{len(actual_non_flat):,}"
)

UP/DOWN accuracy excluding FLAT: 59.26%
Non-flat test observations: 128,141

In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test_cls,
    pred_direction_encoded
)

print("Rows = Actual")
print("Columns = Predicted")

print("\nLabels:", list(label_encoder.classes_))
print(cm)

Rows = Actual
Columns = Predicted

Labels: [np.str_('down'), np.str_('flat'), np.str_('up')]
[[37643  7168 17083]
 [14349 22931 14555]
 [17899 10050 38298]]

In [28]:
# Prediction probabilities for DOWN / FLAT / UP

probabilities = classifier.predict_proba(
    X_test_cls
)

print("Probability shape:", probabilities.shape)

print("\nFirst 5 probability rows:")
print(probabilities[:5])

print("\nClass order:")
print(label_encoder.classes_)

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
Probability shape: (179976, 3)

First 5 probability rows:
[[0.44953254 0.10197502 0.44849244]
 [0.48801903 0.10096031 0.41102066]
 [0.215994   0.10170511 0.68230089]
 [0.27722159 0.10537852 0.61739989]
 [0.43607928 0.08682986 0.47709086]]

Class order:
['down' 'flat' 'up']

In [29]:
# Create a clean test prediction table

results = test[
    [
        "report_date",
        "target_date",
        "market_name",
        "commodity_name",
        "modal_price",
        "target_price",
        "direction"
    ]
].copy()

# Regression prediction
results["predicted_price"] = pred_price

# Classification prediction
results["predicted_direction"] = pred_direction

# Probability of each class
results["prob_down"] = probabilities[:, 0]
results["prob_flat"] = probabilities[:, 1]
results["prob_up"] = probabilities[:, 2]

# Highest probability = model confidence
results["direction_confidence"] = probabilities.max(axis=1)

print(results.head(10))

    report_date target_date   market_name commodity_name  modal_price  \
792  2026-05-08  2026-05-21  APMC Aatpadi    Pomegranate       8500.0
793  2026-05-10  2026-05-22  APMC Aatpadi    Pomegranate       9000.0
794  2026-05-14  2026-05-25  APMC Aatpadi    Pomegranate       7200.0
802  2026-06-01  2026-06-14  APMC Aatpadi    Pomegranate       8000.0
803  2026-06-02  2026-06-15  APMC Aatpadi    Pomegranate       8700.0
804  2026-06-07  2026-06-17  APMC Aatpadi    Pomegranate      10500.0
805  2026-06-08  2026-06-21  APMC Aatpadi    Pomegranate       9000.0
806  2026-06-09  2026-06-23  APMC Aatpadi    Pomegranate       9000.0
807  2026-06-10  2026-06-24  APMC Aatpadi    Pomegranate       9200.0
808  2026-06-11  2026-06-25  APMC Aatpadi    Pomegranate       8200.0

     target_price direction  predicted_price predicted_direction  prob_down  \
792        7500.0      down      8581.504726                down   0.449533
793        9200.0        up      8821.304163                down   0.488019
794        7000.0      down      8287.749464                  up   0.215994
802        9000.0        up      8021.424403                  up   0.277222
803        8700.0      flat      8502.875358                  up   0.436079
804       10000.0      down      9029.418526                down   0.524655
805       11300.0        up      9130.358014                  up   0.400516
806       10000.0        up      9155.493458                  up   0.404441
807        9300.0      flat      9345.709318                  up   0.382294
808        8500.0        up      8952.606469                  up   0.266342

     prob_flat   prob_up  direction_confidence
792   0.101975  0.448492              0.449533
793   0.100960  0.411021              0.488019
794   0.101705  0.682301              0.682301
802   0.105379  0.617400              0.617400
803   0.086830  0.477091              0.477091
804   0.093031  0.382314              0.524655
805   0.091360  0.508124              0.508124
806   0.089410  0.506149              0.506149
807   0.095076  0.522630              0.522630
808   0.086999  0.646658              0.646658

In [30]:
# Expected percentage change according to the regression model

results["predicted_pct_change"] = (
    (
        results["predicted_price"]
        - results["modal_price"]
    )
    / results["modal_price"]
) * 100

print(
    results[
        [
            "commodity_name",
            "market_name",
            "report_date",
            "modal_price",
            "predicted_price",
            "predicted_pct_change",
            "predicted_direction",
            "direction_confidence"
        ]
    ].head(10)
)

    commodity_name   market_name report_date  modal_price  predicted_price  \
792    Pomegranate  APMC Aatpadi  2026-05-08       8500.0      8581.504726
793    Pomegranate  APMC Aatpadi  2026-05-10       9000.0      8821.304163
794    Pomegranate  APMC Aatpadi  2026-05-14       7200.0      8287.749464
802    Pomegranate  APMC Aatpadi  2026-06-01       8000.0      8021.424403
803    Pomegranate  APMC Aatpadi  2026-06-02       8700.0      8502.875358
804    Pomegranate  APMC Aatpadi  2026-06-07      10500.0      9029.418526
805    Pomegranate  APMC Aatpadi  2026-06-08       9000.0      9130.358014
806    Pomegranate  APMC Aatpadi  2026-06-09       9000.0      9155.493458
807    Pomegranate  APMC Aatpadi  2026-06-10       9200.0      9345.709318
808    Pomegranate  APMC Aatpadi  2026-06-11       8200.0      8952.606469

     predicted_pct_change predicted_direction  direction_confidence
792              0.958879                down              0.449533
793             -1.985509                down              0.488019
794             15.107631                  up              0.682301
802              0.267805                  up              0.617400
803             -2.265800                  up              0.477091
804            -14.005538                down              0.524655
805              1.448422                  up              0.508124
806              1.727705                  up              0.506149
807              1.583797                  up              0.522630
808              9.178128                  up              0.646658

In [31]:
def make_recommendation(row):

    if (
        row["predicted_direction"] == "up"
        and row["direction_confidence"] >= 0.60
    ):
        return "HOLD"

    elif (
        row["predicted_direction"] == "down"
        and row["direction_confidence"] >= 0.60
    ):
        return "SELL"

    else:
        return "NO STRONG SIGNAL"


results["recommendation"] = results.apply(
    make_recommendation,
    axis=1
)

print("Recommendation counts:")
print(results["recommendation"].value_counts())

print("\nExamples:")
print(
    results[
        [
            "commodity_name",
            "market_name",
            "modal_price",
            "predicted_price",
            "predicted_pct_change",
            "predicted_direction",
            "direction_confidence",
            "recommendation"
        ]
    ].head(20)
)

Recommendation counts:
recommendation
NO STRONG SIGNAL    133497
HOLD                 24582
SELL                 21897
Name: count, dtype: int64

Examples:
    commodity_name   market_name  modal_price  predicted_price  \
792    Pomegranate  APMC Aatpadi       8500.0      8581.504726
793    Pomegranate  APMC Aatpadi       9000.0      8821.304163
794    Pomegranate  APMC Aatpadi       7200.0      8287.749464
802    Pomegranate  APMC Aatpadi       8000.0      8021.424403
803    Pomegranate  APMC Aatpadi       8700.0      8502.875358
804    Pomegranate  APMC Aatpadi      10500.0      9029.418526
805    Pomegranate  APMC Aatpadi       9000.0      9130.358014
806    Pomegranate  APMC Aatpadi       9000.0      9155.493458
807    Pomegranate  APMC Aatpadi       9200.0      9345.709318
808    Pomegranate  APMC Aatpadi       8200.0      8952.606469
809    Pomegranate  APMC Aatpadi       9000.0      9057.004531
811    Pomegranate  APMC Aatpadi      10000.0      9543.900073
812    Pomegranate  APMC Aatpadi      11300.0     10126.790441
813    Pomegranate  APMC Aatpadi      10000.0     10184.936563
814    Pomegranate  APMC Aatpadi       9300.0      9890.813701
815    Pomegranate  APMC Aatpadi       8500.0      9268.325216
816    Pomegranate  APMC Aatpadi      10500.0      9692.267472
817    Pomegranate  APMC Aatpadi       9500.0      9640.406740
818    Pomegranate  APMC Aatpadi       9500.0      9746.862337
819    Pomegranate  APMC Aatpadi       9500.0      9608.288710

     predicted_pct_change predicted_direction  direction_confidence  \
792              0.958879                down              0.449533
793             -1.985509                down              0.488019
794             15.107631                  up              0.682301
802              0.267805                  up              0.617400
803             -2.265800                  up              0.477091
804            -14.005538                down              0.524655
805              1.448422                  up              0.508124
806              1.727705                  up              0.506149
807              1.583797                  up              0.522630
808              9.178128                  up              0.646658
809              0.633384                  up              0.505108
811             -4.560999                down              0.510391
812            -10.382385                down              0.619763
813              1.849366                  up              0.464577
814              6.352835                  up              0.658942
815              9.039120                  up              0.685049
816             -7.692691                down              0.519893
817              1.477966                  up              0.504979
818              2.598551                  up              0.536471
819              1.139881                  up              0.525281

       recommendation
792  NO STRONG SIGNAL
793  NO STRONG SIGNAL
794              HOLD
802              HOLD
803  NO STRONG SIGNAL
804  NO STRONG SIGNAL
805  NO STRONG SIGNAL
806  NO STRONG SIGNAL
807  NO STRONG SIGNAL
808              HOLD
809  NO STRONG SIGNAL
811  NO STRONG SIGNAL
812              SELL
813  NO STRONG SIGNAL
814              HOLD
815              HOLD
816  NO STRONG SIGNAL
817  NO STRONG SIGNAL
818  NO STRONG SIGNAL
819  NO STRONG SIGNAL

In [32]:
# Evaluate only the recommendations where the system
# actually made a decision.

decision_mask = results["recommendation"].isin(
    ["HOLD", "SELL"]
)

decision_results = results.loc[
    decision_mask
].copy()

# Actual direction
decision_results["correct_direction"] = (
    decision_results["predicted_direction"]
    == decision_results["direction"]
)

print("Total recommendations:", len(results))
print("HOLD/SELL decisions:", len(decision_results))

print("\nDirection accuracy on HOLD/SELL decisions:")
print(
    decision_results["correct_direction"].mean() * 100
)

print("\nAccuracy by recommendation:")
print(
    decision_results
    .groupby("recommendation")["correct_direction"]
    .mean()
    .mul(100)
)

Total recommendations: 179976
HOLD/SELL decisions: 46479

Direction accuracy on HOLD/SELL decisions:
68.69984293982229

Accuracy by recommendation:
recommendation
HOLD    68.289806
SELL    69.160159
Name: correct_direction, dtype: float64

In [33]:
# Check agreement between regression-implied movement
# and classification direction.

results["regression_direction"] = np.select(
    [
        results["predicted_pct_change"] < -2,
        results["predicted_pct_change"] > 2
    ],
    [
        "down",
        "up"
    ],
    default="flat"
)

results["models_agree"] = (
    results["regression_direction"]
    == results["predicted_direction"]
)

print("Model agreement:")
print(
    results["models_agree"].value_counts()
)

print("\nAgreement percentage:")
print(
    results["models_agree"].mean() * 100
)

Model agreement:
models_agree
True     130330
False     49646
Name: count, dtype: int64

Agreement percentage:
72.41521091701115

In [34]:
def make_strict_recommendation(row):

    if (
        row["predicted_direction"] == "up"
        and row["regression_direction"] == "up"
        and row["direction_confidence"] >= 0.60
    ):
        return "HOLD"

    elif (
        row["predicted_direction"] == "down"
        and row["regression_direction"] == "down"
        and row["direction_confidence"] >= 0.60
    ):
        return "SELL"

    else:
        return "NO STRONG SIGNAL"


results["strict_recommendation"] = results.apply(
    make_strict_recommendation,
    axis=1
)

print("Strict recommendation counts:")
print(
    results["strict_recommendation"].value_counts()
)

Strict recommendation counts:
strict_recommendation
NO STRONG SIGNAL    134532
HOLD                 24053
SELL                 21391
Name: count, dtype: int64

In [35]:
# Naive directional baseline:
# predict the future direction from the previous price movement.

naive_direction = np.where(
    test["modal_price"] > test["price_lag_1"],
    "up",
    np.where(
        test["modal_price"] < test["price_lag_1"],
        "down",
        "flat"
    )
)

naive_direction_accuracy = (
    naive_direction == test["direction"].astype(str).values
).mean()

print(
    f"Naive direction accuracy: "
    f"{naive_direction_accuracy * 100:.2f}%"
)

non_flat_mask_naive = (
    test["direction"].astype(str) != "flat"
)

naive_non_flat_accuracy = (
    naive_direction[non_flat_mask_naive]
    == test.loc[non_flat_mask_naive, "direction"].astype(str).values
).mean()

print(
    f"Naive UP/DOWN accuracy: "
    f"{naive_non_flat_accuracy * 100:.2f}%"
)

Naive direction accuracy: 32.05%
Naive UP/DOWN accuracy: 27.95%

In [36]:
# Direction performance by commodity on the test set

crop_results = []

for crop, group in test.groupby("commodity_name"):

    idx = group.index

    actual = group["direction"].astype(str).values
    predicted = pd.Series(
        pred_direction,
        index=test.index
    ).loc[idx].values

    overall_acc = (
        predicted == actual
    ).mean()

    non_flat = actual != "flat"

    if non_flat.sum() > 0:
        non_flat_acc = (
            predicted[non_flat] == actual[non_flat]
        ).mean()
    else:
        non_flat_acc = np.nan

    crop_results.append({
        "commodity": crop,
        "test_rows": len(group),
        "overall_accuracy": overall_acc,
        "up_down_accuracy": non_flat_acc
    })

per_crop_accuracy = (
    pd.DataFrame(crop_results)
    .sort_values(
        "up_down_accuracy",
        ascending=False
    )
)

print(per_crop_accuracy.head(20))

C:\Users\hp\AppData\Local\Temp\ipykernel_11512\880725385.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for crop, group in test.groupby("commodity_name"):
C:\Users\hp\AppData\Local\Temp\ipykernel_11512\880725385.py:17: RuntimeWarning: Mean of empty slice.
  ).mean()
c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\numpy\_core\_methods.py:144: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

                  commodity  test_rows  overall_accuracy  up_down_accuracy
75    Pointed gourd(Parval)        302          0.576159          0.764444
34                Drumstick       2585          0.605803          0.756286
60          Mango(Raw-Ripe)        963          0.603323          0.738462
74                     Plum         59          0.525424          0.738095
71           Pear(Marasebu)        168          0.607143          0.728571
88                 Seetapal        217          0.594470          0.724719
8                  Beetroot       1560          0.602564          0.708955
59                    Mango        784          0.588010          0.708006
6            Banana - Green        177          0.519774          0.707692
96             Sweet Potato        429          0.557110          0.705329
72                 Peas Wet       1482          0.572200          0.702748
100                  Tomato       6541          0.574683          0.698541
85         Ridgeguard(Tori)       3295          0.569651          0.697473
23              Cauliflower       5742          0.569488          0.696774
7                     Beans       2383          0.580361          0.694626
67              Onion Green       1391          0.552840          0.692669
36   French Beans(Frasbean)        284          0.626761          0.689922
57     Little gourd(Kundru)       1052          0.581749          0.689576
48                     Guar       4208          0.551331          0.688323
18                  Cabbage       5823          0.582689          0.688002

In [37]:
# Evaluate HOLD/SELL recommendations against baselines
# using the original test dataframe for price_lag_1.

issued_mask = results["recommendation"].isin(
    ["HOLD", "SELL"]
)

issued = results.loc[issued_mask].copy()

# Map recommendation to predicted direction
issued["predicted_action_direction"] = issued[
    "recommendation"
].map({
    "HOLD": "up",
    "SELL": "down"
})

# Actual direction
issued["actual_direction"] = issued["direction"].astype(str)

# -----------------------------
# 1. Model accuracy
# -----------------------------

model_action_accuracy = (
    issued["predicted_action_direction"]
    == issued["actual_direction"]
).mean()

# -----------------------------
# 2. Majority-class baseline
# -----------------------------

actual_counts = issued["actual_direction"].value_counts()

majority_direction = actual_counts.index[0]

majority_accuracy = (
    issued["actual_direction"]
    == majority_direction
).mean()

# -----------------------------
# 3. Naive previous-price baseline
# -----------------------------

# Get price_lag_1 from the original test dataframe
issued_lag1 = test.loc[issued.index, "price_lag_1"]

naive_action_direction = np.where(
    issued["modal_price"].values > issued_lag1.values,
    "up",
    np.where(
        issued["modal_price"].values < issued_lag1.values,
        "down",
        "flat"
    )
)

naive_accuracy = (
    naive_action_direction
    == issued["actual_direction"].values
).mean()

# -----------------------------
# Results
# -----------------------------

print("Issued HOLD/SELL decisions:", len(issued))

print("\nActual direction distribution:")
print(actual_counts)

print("\nMODEL")
print(f"Accuracy: {model_action_accuracy * 100:.2f}%")

print("\nMAJORITY BASELINE")
print(
    f"Always predict '{majority_direction}': "
    f"{majority_accuracy * 100:.2f}%"
)

print("\nNAIVE PREVIOUS-PRICE BASELINE")
print(
    f"Accuracy: {naive_accuracy * 100:.2f}%"
)

Issued HOLD/SELL decisions: 46479

Actual direction distribution:
actual_direction
up      20612
down    19426
flat     6441
Name: count, dtype: int64

MODEL
Accuracy: 68.70%

MAJORITY BASELINE
Always predict 'up': 44.35%

NAIVE PREVIOUS-PRICE BASELINE
Accuracy: 22.83%

evaluating regression model

In [38]:
# Regression performance by commodity
# Compare LightGBM against the naive current-price baseline.

reg_test = test[
    [
        "commodity_name",
        "target_price",
        "modal_price"
    ]
].copy()

reg_test["predicted_price"] = pred_price

reg_test["abs_error_model"] = (
    reg_test["target_price"]
    - reg_test["predicted_price"]
).abs()

reg_test["abs_error_naive"] = (
    reg_test["target_price"]
    - reg_test["modal_price"]
).abs()

crop_regression = (
    reg_test
    .groupby("commodity_name", observed=True)
    .agg(
        test_rows=("target_price", "size"),
        model_mae=("abs_error_model", "mean"),
        naive_mae=("abs_error_naive", "mean")
    )
    .reset_index()
)

crop_regression["mae_lift"] = (
    crop_regression["naive_mae"]
    - crop_regression["model_mae"]
)

crop_regression["mae_lift_pct"] = (
    crop_regression["mae_lift"]
    / crop_regression["naive_mae"]
) * 100

crop_regression = crop_regression.sort_values(
    "test_rows",
    ascending=False
)

print(crop_regression.head(20))

                commodity_name  test_rows   model_mae   naive_mae   mae_lift  \
102                      Wheat       9105   85.296022   92.921582   7.625560
65                       Onion       8481  226.462648  236.125044   9.662397
10    Bengal Gram(Gram)(Whole)       7098  209.623556  225.688574  16.065018
91                    Soyabean       6851  357.502907  344.318786 -13.184121
82   Red gram/Arhar/Tur(whole)       6769  312.329279  321.653494   9.324214
99                      Tomato       6541  307.622165  357.886256  50.264091
11       Bhindi(Ladies Finger)       6127  502.032140  571.800555  69.768415
17                     Brinjal       6092  432.844314  463.825181  30.980866
41                Green Chilli       6014  640.596786  700.526605  59.929818
18                     Cabbage       5823  187.213147  212.337455  25.124308
23                 Cauliflower       5742  334.796899  374.945315  40.148416
32            Cucumbar(Kheera)       5660  347.682820  381.571731  33.888911
12                Bitter gourd       4696  531.100013  607.629685  76.529672
76                      Potato       4676  108.339618   95.662318 -12.677300
51              Jowar(Sorghum)       4489  264.137387  291.468144  27.330758
47                        Guar       4208  861.796550  935.934886  74.138336
39               Ginger(Green)       3907  981.015775  979.602764  -1.413011
26             Chilly Capsicum       3800  525.293117  596.429211  71.136094
16                Bottle gourd       3795  302.243741  334.233992  31.990251
20                      Carrot       3644  270.025220  298.702525  28.677305

     mae_lift_pct
102      8.206446
65       4.092068
10       7.118224
91      -3.829045
82       2.898838
99      14.044711
11      12.201530
17       6.679427
41       8.554967
18      11.832255
23      10.707806
32       8.881400
12      12.594788
76     -13.252135
51       9.376928
47       7.921313
39      -0.144243
26      11.926997
16       9.571214
20       9.600624

In [39]:
priority_crops = [
    "Onion",
    "Tomato",
    "Soyabean",
    "Wheat",
    "Red gram/Arhar/Tur(whole)",
    "Cotton"
]

priority_regression = crop_regression[
    crop_regression["commodity_name"].isin(priority_crops)
].copy()

priority_regression = priority_regression.sort_values(
    "mae_lift_pct",
    ascending=False
)

print(priority_regression.to_string(index=False))

           commodity_name  test_rows  model_mae  naive_mae   mae_lift  mae_lift_pct
                   Tomato       6541 307.622165 357.886256  50.264091     14.044711
                    Wheat       9105  85.296022  92.921582   7.625560      8.206446
                    Onion       8481 226.462648 236.125044   9.662397      4.092068
Red gram/Arhar/Tur(whole)       6769 312.329279 321.653494   9.324214      2.898838
                 Soyabean       6851 357.502907 344.318786 -13.184121     -3.829045
                   Cotton       1420 234.299430 204.342444 -29.956986    -14.660188

In [40]:
priority_direction = per_crop_accuracy[
    per_crop_accuracy["commodity"].isin(priority_crops)
].copy()

priority_direction = priority_direction.sort_values(
    "up_down_accuracy",
    ascending=False
)

print(
    priority_direction.to_string(index=False)
)

                commodity  test_rows  overall_accuracy  up_down_accuracy
                   Tomato       6541          0.574683          0.698541
                    Onion       8481          0.562552          0.655294
                    Wheat       9105          0.528281          0.402926
                 Soyabean       6851          0.362429          0.337627
Red gram/Arhar/Tur(whole)       6769          0.401536          0.307445
                   Cotton       1420          0.542958          0.012422

In [41]:
# Compare actual and predicted direction distributions
# for the SIH priority crops.

priority_check = []

for crop in priority_crops:

    mask = test["commodity_name"] == crop

    actual = test.loc[mask, "direction"].astype(str)

    predicted = pd.Series(
        pred_direction,
        index=test.index
    ).loc[mask]

    priority_check.append({
        "commodity": crop,
        "n_test": len(actual),

        "actual_down_pct": (
            (actual == "down").mean() * 100
        ),

        "actual_flat_pct": (
            (actual == "flat").mean() * 100
        ),

        "actual_up_pct": (
            (actual == "up").mean() * 100
        ),

        "pred_down_pct": (
            (predicted == "down").mean() * 100
        ),

        "pred_flat_pct": (
            (predicted == "flat").mean() * 100
        ),

        "pred_up_pct": (
            (predicted == "up").mean() * 100
        )
    })

priority_check = pd.DataFrame(priority_check)

print(
    priority_check.to_string(index=False)
)

                commodity  n_test  actual_down_pct  actual_flat_pct  actual_up_pct  pred_down_pct  pred_flat_pct  pred_up_pct
                    Onion    8481        32.731989        16.707935      50.560075      44.063200       3.478363    52.458437
                   Tomato    6541        41.752026        20.379147      37.868827      49.977068       3.776181    46.246751
                 Soyabean    6851        33.571741        25.207999      41.220260      59.436579      38.052839     2.510582
                    Wheat    9105        24.986271        41.449753      33.563976      15.881384      57.353103    26.765513
Red gram/Arhar/Tur(whole)    6769        27.153198        40.271827      32.574974      48.515290      47.274339     4.210371
                   Cotton    1420        17.957746        54.647887      27.394366       1.267606      98.028169     0.704225

In [42]:
# Check how each priority crop is distributed in the TRAINING data.

train_crop_distribution = []

for crop in priority_crops:

    subset = train[
        train["commodity_name"] == crop
    ]

    counts = (
        subset["direction"]
        .astype(str)
        .value_counts()
    )

    total = len(subset)

    train_crop_distribution.append({
        "commodity": crop,
        "train_rows": total,

        "down_pct": (
            counts.get("down", 0) / total * 100
            if total > 0 else np.nan
        ),

        "flat_pct": (
            counts.get("flat", 0) / total * 100
            if total > 0 else np.nan
        ),

        "up_pct": (
            counts.get("up", 0) / total * 100
            if total > 0 else np.nan
        )
    })

train_crop_distribution = pd.DataFrame(
    train_crop_distribution
)

print(
    train_crop_distribution.to_string(index=False)
)

                commodity  train_rows  down_pct  flat_pct    up_pct
                    Onion       43334 42.276273 15.237458 42.486269
                   Tomato       39036 41.064658 16.725587 42.209755
                 Soyabean       52955 28.237183 44.579360 27.183458
                    Wheat       51596 28.304520 39.210404 32.485076
Red gram/Arhar/Tur(whole)       32022 26.335020 40.325401 33.339579
                   Cotton       12085 20.215143 57.550683 22.234175

In [43]:
# Check average prediction probabilities and confidence
# for each priority crop.

confidence_results = []

for crop in priority_crops:

    mask = test["commodity_name"] == crop

    if mask.sum() == 0:
        continue

    probs_crop = probabilities[mask.values]

    confidence_results.append({
        "commodity": crop,
        "test_rows": mask.sum(),

        "avg_prob_down": probs_crop[:, 0].mean(),
        "avg_prob_flat": probs_crop[:, 1].mean(),
        "avg_prob_up": probs_crop[:, 2].mean(),

        "avg_confidence": probs_crop.max(axis=1).mean()
    })

confidence_results = pd.DataFrame(
    confidence_results
)

print(
    confidence_results.to_string(index=False)
)

                commodity  test_rows  avg_prob_down  avg_prob_flat  avg_prob_up  avg_confidence
                    Onion       8481       0.392785       0.173502     0.433713        0.543000
                   Tomato       6541       0.416639       0.182679     0.400682        0.534353
                 Soyabean       6851       0.452913       0.394036     0.153051        0.520914
                    Wheat       9105       0.249467       0.443582     0.306951        0.538714
Red gram/Arhar/Tur(whole)       6769       0.404097       0.393474     0.202430        0.488620
                   Cotton       1420       0.183998       0.674011     0.141992        0.676632

In [44]:
importance = pd.DataFrame({
    "feature": FEATURES,
    "importance": classifier.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

print(importance.to_string(index=False))

               feature  importance
           market_name       16701
        commodity_name       11987
           modal_price        6708
          week_of_year        6379
                  year        2672
    price_roll_mean_30        1960
     price_roll_mean_7        1874
             max_price        1868
                 month        1684
      price_roll_std_7        1610
           price_lag_1        1585
             min_price        1529
           price_lag_2        1037
              arrivals         855
           price_lag_3         745
           price_lag_7         723
           day_of_week          93
days_since_last_report          68

In [45]:
# Commodity-level historical price context
# Calculated using only previous observations to avoid leakage.

commodity_grp = (
    df_daily
    .groupby("commodity_name")["modal_price"]
)

df_daily["commodity_roll_mean_30"] = (
    commodity_grp
    .transform(
        lambda s: s.shift(1)
        .rolling(30, min_periods=10)
        .mean()
    )
)

df_daily["commodity_roll_mean_90"] = (
    commodity_grp
    .transform(
        lambda s: s.shift(1)
        .rolling(90, min_periods=30)
        .mean()
    )
)

df_daily["price_vs_commodity_30"] = (
    df_daily["modal_price"]
    / df_daily["commodity_roll_mean_30"]
)

df_daily["price_vs_commodity_90"] = (
    df_daily["modal_price"]
    / df_daily["commodity_roll_mean_90"]
)

print(
    df_daily[
        [
            "commodity_name",
            "report_date",
            "modal_price",
            "commodity_roll_mean_30",
            "commodity_roll_mean_90",
            "price_vs_commodity_30",
            "price_vs_commodity_90"
        ]
    ].head(20)
)

   commodity_name report_date  modal_price  commodity_roll_mean_30  \
0     Pomegranate  2021-01-14      13500.0                     NaN
1     Pomegranate  2021-01-15      13500.0                     NaN
2     Pomegranate  2021-01-17      15000.0                     NaN
3     Pomegranate  2021-01-18      12000.0                     NaN
4     Pomegranate  2021-01-19      12500.0                     NaN
5     Pomegranate  2021-01-20      13500.0                     NaN
6     Pomegranate  2021-01-21      13500.0                     NaN
7     Pomegranate  2021-01-22      10500.0                     NaN
8     Pomegranate  2021-01-24      12500.0                     NaN
9     Pomegranate  2021-01-26      15000.0                     NaN
10    Pomegranate  2021-02-04      18500.0            13150.000000
11    Pomegranate  2021-02-12      18500.0            13636.363636
12    Pomegranate  2021-02-15      18500.0            14041.666667
13    Pomegranate  2021-02-19      16500.0            14384.615385
14    Pomegranate  2021-02-22      18500.0            14535.714286
15    Pomegranate  2021-02-23      13500.0            14800.000000
16    Pomegranate  2021-02-24      13500.0            14718.750000
17    Pomegranate  2021-02-25      11500.0            14647.058824
18    Pomegranate  2021-02-26      13500.0            14472.222222
19    Pomegranate  2021-02-28      13500.0            14421.052632

    commodity_roll_mean_90  price_vs_commodity_30  price_vs_commodity_90
0                      NaN                    NaN                    NaN
1                      NaN                    NaN                    NaN
2                      NaN                    NaN                    NaN
3                      NaN                    NaN                    NaN
4                      NaN                    NaN                    NaN
5                      NaN                    NaN                    NaN
6                      NaN                    NaN                    NaN
7                      NaN                    NaN                    NaN
8                      NaN                    NaN                    NaN
9                      NaN                    NaN                    NaN
10                     NaN               1.406844                    NaN
11                     NaN               1.356667                    NaN
12                     NaN               1.317507                    NaN
13                     NaN               1.147059                    NaN
14                     NaN               1.272727                    NaN
15                     NaN               0.912162                    NaN
16                     NaN               0.917197                    NaN
17                     NaN               0.785141                    NaN
18                     NaN               0.932821                    NaN
19                     NaN               0.936131                    NaN

In [46]:
FEATURES = [
    "market_name",
    "commodity_name",

    "modal_price",
    "min_price",
    "max_price",
    "arrivals",

    "days_since_last_report",

    "price_lag_1",
    "price_lag_2",
    "price_lag_3",
    "price_lag_7",

    "price_roll_mean_7",
    "price_roll_std_7",
    "price_roll_mean_30",

    "commodity_roll_mean_30",
    "commodity_roll_mean_90",
    "price_vs_commodity_30",
    "price_vs_commodity_90",

    "year",
    "month",
    "day_of_week",
    "week_of_year"
]

CATEGORICAL = [
    "market_name",
    "commodity_name"
]

print("Number of features:", len(FEATURES))

for feature in FEATURES:
    print("-", feature)

Number of features: 22
- market_name
- commodity_name
- modal_price
- min_price
- max_price
- arrivals
- days_since_last_report
- price_lag_1
- price_lag_2
- price_lag_3
- price_lag_7
- price_roll_mean_7
- price_roll_std_7
- price_roll_mean_30
- commodity_roll_mean_30
- commodity_roll_mean_90
- price_vs_commodity_30
- price_vs_commodity_90
- year
- month
- day_of_week
- week_of_year

In [47]:
# Rebuild df_model so it includes the new commodity-relative features

df_model = df_daily[
    df_daily["horizon_days"].between(7, 14)
].copy()

df_model = df_model.dropna(
    subset=["target_price"]
).copy()

print("Final modeling rows:", len(df_model))

# Create direction again
df_model["pct_change_7"] = (
    (df_model["target_price"] - df_model["modal_price"])
    / df_model["modal_price"]
)

df_model["direction"] = pd.cut(
    df_model["pct_change_7"],
    bins=[-np.inf, -0.02, 0.02, np.inf],
    labels=["down", "flat", "up"]
)

print("\nDirection distribution:")
print(df_model["direction"].value_counts())

print("\nRequired features missing:")
print(
    [col for col in FEATURES if col not in df_model.columns]
)

Final modeling rows: 1243583

Direction distribution:
direction
up      451224
down    440096
flat    352263
Name: count, dtype: int64

Required features missing:
[]

In [48]:
# Rebuild chronological train / validation / test splits

split_train_end = pd.Timestamp("2025-06-30")
split_val_end = pd.Timestamp("2025-12-31")

train = df_model[
    df_model["report_date"] <= split_train_end
].copy()

val = df_model[
    (df_model["report_date"] > split_train_end) &
    (df_model["report_date"] <= split_val_end)
].copy()

test = df_model[
    df_model["report_date"] > split_val_end
].copy()

print("Train shape:", train.shape)
print("Validation shape:", val.shape)
print("Test shape:", test.shape)

print("\nDate ranges:")

print(
    "Train:",
    train["report_date"].min(),
    "→",
    train["report_date"].max()
)

print(
    "Validation:",
    val["report_date"].min(),
    "→",
    val["report_date"].max()
)

print(
    "Test:",
    test["report_date"].min(),
    "→",
    test["report_date"].max()
)

Train shape: (948244, 30)
Validation shape: (115363, 30)
Test shape: (179976, 30)

Date ranges:
Train: 2021-01-01 00:00:00 → 2025-06-30 00:00:00
Validation: 2025-07-01 00:00:00 → 2025-12-31 00:00:00
Test: 2026-01-01 00:00:00 → 2026-09-06 00:00:00

In [49]:
# Prepare regression features and targets

# Make categorical columns consistent across splits
for col in CATEGORICAL:

    categories = df_model[col].astype("category").cat.categories

    train[col] = pd.Categorical(
        train[col],
        categories=categories
    )

    val[col] = pd.Categorical(
        val[col],
        categories=categories
    )

    test[col] = pd.Categorical(
        test[col],
        categories=categories
    )

X_train_reg = train[FEATURES]
X_val_reg = val[FEATURES]
X_test_reg = test[FEATURES]

y_train_reg = train["target_price"]
y_val_reg = val["target_price"]
y_test_reg = test["target_price"]

print("X_train:", X_train_reg.shape)
print("X_val:", X_val_reg.shape)
print("X_test:", X_test_reg.shape)

print("\ny_train:", y_train_reg.shape)
print("y_val:", y_val_reg.shape)
print("y_test:", y_test_reg.shape)

print("\nMissing values in X_train:")
print(X_train_reg.isna().sum())

X_train: (948244, 22)
X_val: (115363, 22)
X_test: (179976, 22)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

Missing values in X_train:
market_name                  0
commodity_name               0
modal_price                  0
min_price                    0
max_price                    0
arrivals                     0
days_since_last_report     277
price_lag_1                277
price_lag_2                632
price_lag_3               1121
price_lag_7               4900
price_roll_mean_7         1121
price_roll_std_7          1121
price_roll_mean_30        2701
commodity_roll_mean_30     413
commodity_roll_mean_90    1517
price_vs_commodity_30      413
price_vs_commodity_90     1517
year                         0
month                        0
day_of_week                  0
week_of_year                 0
dtype: int64

In [50]:
from lightgbm import LGBMRegressor, early_stopping, log_evaluation

regressor_v2 = LGBMRegressor(
    objective="regression",
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

regressor_v2.fit(
    X_train_reg,
    np.log1p(y_train_reg),

    eval_set=[
        (X_val_reg, np.log1p(y_val_reg))
    ],

    eval_metric="l2",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.078325 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4336
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 22
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Start training from score 7.723530
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.0559672
[200]	valid_0's l2: 0.0522454
[300]	valid_0's l2: 0.0524534
Early stopping, best iteration is:
[201]	valid_0's l2: 0.0522329

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, min_data_in_leaf=100,
              n_estimators=3000, n_jobs=-1, num_leaves=63,
              objective='regression', random_state=42, subsample=0.8)

In [51]:
# Test predictions from the revised regression model

pred_log_v2 = regressor_v2.predict(
    X_test_reg
)

pred_price_v2 = np.expm1(
    pred_log_v2
)

pred_price_v2 = np.maximum(
    pred_price_v2,
    0
)

print("Number of predictions:", len(pred_price_v2))

print("First 10 predictions:")
print(pred_price_v2[:10])

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
Number of predictions: 179976
First 10 predictions:
[8482.27059956 8801.03652247 8227.52920833 8030.10385485 8387.4579816
 9022.12121967 9067.50039311 9092.69390929 9204.21775769 8821.8559351 ]

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Revised LightGBM metrics
mae_v2 = mean_absolute_error(
    y_test_reg,
    pred_price_v2
)

rmse_v2 = np.sqrt(
    mean_squared_error(
        y_test_reg,
        pred_price_v2
    )
)

smape_v2 = (
    100
    * np.mean(
        2 * np.abs(pred_price_v2 - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(pred_price_v2)
            + 1e-8
        )
    )
)

# Naive baseline
naive_pred = test["modal_price"].to_numpy()

naive_mae = mean_absolute_error(
    y_test_reg,
    naive_pred
)

naive_rmse = np.sqrt(
    mean_squared_error(
        y_test_reg,
        naive_pred
    )
)

naive_smape = (
    100
    * np.mean(
        2 * np.abs(naive_pred - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(naive_pred)
            + 1e-8
        )
    )
)

print("REVISED LIGHTGBM")
print(f"MAE   : ₹{mae_v2:,.2f}")
print(f"RMSE  : ₹{rmse_v2:,.2f}")
print(f"sMAPE : {smape_v2:.2f}%")

print("\nNAIVE BASELINE")
print(f"MAE   : ₹{naive_mae:,.2f}")
print(f"RMSE  : ₹{naive_rmse:,.2f}")
print(f"sMAPE : {naive_smape:.2f}%")

REVISED LIGHTGBM
MAE   : ₹448.20
RMSE  : ₹1,220.32
sMAPE : 12.96%

NAIVE BASELINE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

In [53]:
# Create log1p versions of price-scale features.
# Keep categorical features unchanged.

LOG_FEATURES = [
    "modal_price",
    "min_price",
    "max_price",
    "price_lag_1",
    "price_lag_2",
    "price_lag_3",
    "price_lag_7",
    "price_roll_mean_7",
    "price_roll_std_7",
    "price_roll_mean_30",
]

for col in LOG_FEATURES:
    train[f"log_{col}"] = np.log1p(train[col])
    val[f"log_{col}"] = np.log1p(val[col])
    test[f"log_{col}"] = np.log1p(test[col])

LOG_FEATURES_FINAL = [
    "market_name",
    "commodity_name",

    "log_modal_price",
    "log_min_price",
    "log_max_price",

    "arrivals",
    "days_since_last_report",

    "log_price_lag_1",
    "log_price_lag_2",
    "log_price_lag_3",
    "log_price_lag_7",

    "log_price_roll_mean_7",
    "log_price_roll_std_7",
    "log_price_roll_mean_30",

    "year",
    "month",
    "day_of_week",
    "week_of_year"
]

print("Number of features:", len(LOG_FEATURES_FINAL))
print("\nFeatures:")
for feature in LOG_FEATURES_FINAL:
    print("-", feature)

Number of features: 18

Features:
- market_name
- commodity_name
- log_modal_price
- log_min_price
- log_max_price
- arrivals
- days_since_last_report
- log_price_lag_1
- log_price_lag_2
- log_price_lag_3
- log_price_lag_7
- log_price_roll_mean_7
- log_price_roll_std_7
- log_price_roll_mean_30
- year
- month
- day_of_week
- week_of_year

In [54]:
X_train_log = train[LOG_FEATURES_FINAL]
X_val_log = val[LOG_FEATURES_FINAL]
X_test_log = test[LOG_FEATURES_FINAL]

print("X_train:", X_train_log.shape)
print("X_val:", X_val_log.shape)
print("X_test:", X_test_log.shape)

print("\nMissing values in X_train:")
print(X_train_log.isna().sum())

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

Missing values in X_train:
market_name                  0
commodity_name               0
log_modal_price              0
log_min_price                0
log_max_price                0
arrivals                     0
days_since_last_report     277
log_price_lag_1            277
log_price_lag_2            632
log_price_lag_3           1121
log_price_lag_7           4900
log_price_roll_mean_7     1121
log_price_roll_std_7      1121
log_price_roll_mean_30    2701
year                         0
month                        0
day_of_week                  0
week_of_year                 0
dtype: int64

In [55]:
regressor_log = LGBMRegressor(
    objective="regression",
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

regressor_log.fit(
    X_train_log,
    np.log1p(y_train_reg),

    eval_set=[
        (X_val_log, np.log1p(y_val_reg))
    ],

    eval_metric="l2",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012848 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3316
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 18
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Start training from score 7.723530
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.0560245
[200]	valid_0's l2: 0.0527363
[300]	valid_0's l2: 0.0525129
Early stopping, best iteration is:
[298]	valid_0's l2: 0.0524913

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, min_data_in_leaf=100,
              n_estimators=3000, n_jobs=-1, num_leaves=63,
              objective='regression', random_state=42, subsample=0.8)

In [56]:
pred_log_v3 = regressor_log.predict(
    X_test_log
)

pred_price_v3 = np.expm1(
    pred_log_v3
)

pred_price_v3 = np.maximum(
    pred_price_v3,
    0
)

print("Number of predictions:", len(pred_price_v3))
print("First 10 predictions:")
print(pred_price_v3[:10])

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
Number of predictions: 179976
First 10 predictions:
[8600.31887485 8870.34938613 8336.36464339 8170.85912806 8659.15557753
 9196.02941425 9308.93189239 9292.61931776 9492.36543594 9142.31014234]

In [57]:
mae_v3 = mean_absolute_error(
    y_test_reg,
    pred_price_v3
)

rmse_v3 = np.sqrt(
    mean_squared_error(
        y_test_reg,
        pred_price_v3
    )
)

smape_v3 = (
    100
    * np.mean(
        2 * np.abs(pred_price_v3 - y_test_reg)
        /
        (
            np.abs(y_test_reg)
            + np.abs(pred_price_v3)
            + 1e-8
        )
    )
)

print("LOG-FEATURE LIGHTGBM")
print(f"MAE   : ₹{mae_v3:,.2f}")
print(f"RMSE  : ₹{rmse_v3:,.2f}")
print(f"sMAPE : {smape_v3:.2f}%")

print("\nBASELINES")

print("Naive:")
print(f"MAE   : ₹{naive_mae:,.2f}")
print(f"RMSE  : ₹{naive_rmse:,.2f}")
print(f"sMAPE : {naive_smape:.2f}%")

print("\nOriginal LightGBM:")
print(f"MAE   : ₹{mae:,.2f}")
print(f"RMSE  : ₹{rmse:,.2f}")
print(f"sMAPE : {smape:.2f}%")

LOG-FEATURE LIGHTGBM
MAE   : ₹436.93
RMSE  : ₹1,097.29
sMAPE : 12.92%

BASELINES
Naive:
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

Original LightGBM:
MAE   : ₹442.30
RMSE  : ₹1,128.30
sMAPE : 12.94%

In [58]:
# Regression performance of the LOG-feature model
# for the SIH priority crops.

reg_test_v3 = test[
    [
        "commodity_name",
        "target_price",
        "modal_price"
    ]
].copy()

reg_test_v3["predicted_price"] = pred_price_v3

reg_test_v3["abs_error_model"] = (
    reg_test_v3["target_price"]
    - reg_test_v3["predicted_price"]
).abs()

reg_test_v3["abs_error_naive"] = (
    reg_test_v3["target_price"]
    - reg_test_v3["modal_price"]
).abs()

crop_regression_v3 = (
    reg_test_v3
    .groupby("commodity_name", observed=True)
    .agg(
        test_rows=("target_price", "size"),
        model_mae=("abs_error_model", "mean"),
        naive_mae=("abs_error_naive", "mean")
    )
    .reset_index()
)

crop_regression_v3["mae_lift_pct"] = (
    (
        crop_regression_v3["naive_mae"]
        - crop_regression_v3["model_mae"]
    )
    / crop_regression_v3["naive_mae"]
) * 100

priority_regression_v3 = (
    crop_regression_v3[
        crop_regression_v3["commodity_name"].isin(priority_crops)
    ]
    .sort_values("mae_lift_pct", ascending=False)
)

print(
    priority_regression_v3.to_string(index=False)
)

           commodity_name  test_rows  model_mae  naive_mae  mae_lift_pct
                   Tomato       6541 310.691428 357.886256     13.187103
                    Wheat       9105  85.508216  92.921582      7.978088
                    Onion       8481 223.185495 236.125044      5.479956
Red gram/Arhar/Tur(whole)       6769 313.132876 321.653494      2.649005
                 Soyabean       6851 360.570092 344.318786     -4.719843
                   Cotton       1420 237.795183 204.342444    -16.370921

In [61]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit(["down", "flat", "up"])

train["direction_encoded"] = label_encoder.transform(
    train["direction"]
)

val["direction_encoded"] = label_encoder.transform(
    val["direction"]
)

test["direction_encoded"] = label_encoder.transform(
    test["direction"]
)

print("Class mapping:")
print(
    dict(
        zip(
            label_encoder.classes_,
            range(len(label_encoder.classes_))
        )
    )
)

print("\nTrain class counts:")
print(
    train["direction"].value_counts()
)

Class mapping:
{np.str_('down'): 0, np.str_('flat'): 1, np.str_('up'): 2}

Train class counts:
direction
up      344926
down    335103
flat    268215
Name: count, dtype: int64

In [62]:
X_train_cls_log = train[LOG_FEATURES_FINAL]
X_val_cls_log = val[LOG_FEATURES_FINAL]
X_test_cls_log = test[LOG_FEATURES_FINAL]

y_train_cls = train["direction_encoded"]
y_val_cls = val["direction_encoded"]
y_test_cls = test["direction_encoded"]

print("X_train:", X_train_cls_log.shape)
print("X_val:", X_val_cls_log.shape)
print("X_test:", X_test_cls_log.shape)

print("\ny_train:", y_train_cls.shape)
print("y_val:", y_val_cls.shape)
print("y_test:", y_test_cls.shape)

X_train: (948244, 18)
X_val: (115363, 18)
X_test: (179976, 18)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [63]:
from lightgbm import LGBMClassifier, early_stopping, log_evaluation

classifier_log = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=3000,
    learning_rate=0.05,
    num_leaves=63,
    min_data_in_leaf=200,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

classifier_log.fit(
    X_train_cls_log,
    y_train_cls,

    eval_set=[
        (X_val_cls_log, y_val_cls)
    ],

    eval_metric="multi_logloss",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019634 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3316
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 18
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Start training from score -1.040174
[LightGBM] [Info] Start training from score -1.262823
[LightGBM] [Info] Start training from score -1.011282
Training until validation scores don't improve for 100 rounds
[100]	valid_0's multi_logloss: 0.932729
[200]	valid_0's multi_logloss: 0.922476
[300]	valid_0's multi_logloss: 0.921393
[400]	valid_0's multi_logloss: 0.921641
Early stopping, best iteration is:
[329]	valid_0's multi_logloss: 0.921257

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, min_data_in_leaf=200,
               n_estimators=3000, n_jobs=-1, num_class=3, num_leaves=63,
               objective='multiclass', random_state=42, subsample=0.8)

In [64]:
pred_direction_log_encoded = (
    classifier_log
    .predict(X_test_cls_log)
    .astype(int)
    .ravel()
)

pred_direction_log = (
    label_encoder.inverse_transform(
        pred_direction_log_encoded
    )
)

print(
    "Number of predictions:",
    len(pred_direction_log)
)

print("\nFirst 20 predictions:")
print(pred_direction_log[:20])

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
Number of predictions: 179976

First 20 predictions:
['up' 'down' 'up' 'up' 'up' 'down' 'up' 'up' 'up' 'up' 'up' 'down' 'down'
 'up' 'up' 'up' 'down' 'up' 'up' 'up']

In [65]:
from sklearn.metrics import accuracy_score

accuracy_log = accuracy_score(
    y_test_cls,
    pred_direction_log_encoded
)

print(
    f"Log-feature overall accuracy: "
    f"{accuracy_log * 100:.2f}%"
)

# UP/DOWN accuracy excluding FLAT
non_flat_mask = test["direction"].astype(str) != "flat"

actual_non_flat = (
    test.loc[non_flat_mask, "direction"]
    .astype(str)
    .values
)

pred_non_flat = (
    pd.Series(
        pred_direction_log,
        index=test.index
    )
    .loc[non_flat_mask]
    .values
)

non_flat_accuracy_log = (
    actual_non_flat == pred_non_flat
).mean()

print(
    f"Log-feature UP/DOWN accuracy: "
    f"{non_flat_accuracy_log * 100:.2f}%"
)

print("\nOriginal classifier:")
print("Overall accuracy: 54.94%")
print("UP/DOWN accuracy: 59.26%")

Log-feature overall accuracy: 55.06%
Log-feature UP/DOWN accuracy: 59.28%

Original classifier:
Overall accuracy: 54.94%
UP/DOWN accuracy: 59.26%

In [66]:
# ------------------------------------------------------------
# SAME-DAY CROSS-MARKET FEATURES
# ------------------------------------------------------------
#
# For each commodity + date:
#   - median price across OTHER markets
#   - mean price across OTHER markets
#   - current market's deviation from other-market median
#   - fraction of OTHER markets that moved up
#   - fraction of OTHER markets that moved down
#
# These are calculated before target creation and use only
# information available on the current report date.
# ------------------------------------------------------------

cross = df_daily[
    [
        "market_name",
        "commodity_name",
        "report_date",
        "modal_price"
    ]
].copy()

# Previous price for each market + commodity
cross["prev_price"] = (
    cross
    .groupby(["market_name", "commodity_name"])["modal_price"]
    .shift(1)
)

# Same-day commodity statistics across all markets
cross["same_day_market_count"] = (
    cross
    .groupby(["commodity_name", "report_date"])["market_name"]
    .transform("nunique")
)

cross["same_day_price_sum"] = (
    cross
    .groupby(["commodity_name", "report_date"])["modal_price"]
    .transform("sum")
)

cross["same_day_price_mean_all"] = (
    cross
    .groupby(["commodity_name", "report_date"])["modal_price"]
    .transform("mean")
)

cross["same_day_price_median_all"] = (
    cross
    .groupby(["commodity_name", "report_date"])["modal_price"]
    .transform("median")
)

# Exclude the current market from the mean
cross["other_market_count"] = (
    cross["same_day_market_count"] - 1
)

cross["cross_market_mean"] = np.where(
    cross["other_market_count"] > 0,
    (
        cross["same_day_price_sum"]
        - cross["modal_price"]
    ) / cross["other_market_count"],
    np.nan
)

# Current market relative to same-day statewide median
cross["price_vs_market_median"] = (
    cross["modal_price"]
    / cross["same_day_price_median_all"]
)

cross["price_vs_other_market_mean"] = (
    cross["modal_price"]
    / cross["cross_market_mean"]
)

# Current market's own previous movement
cross["current_market_pct_change"] = (
    (cross["modal_price"] - cross["prev_price"])
    / cross["prev_price"]
)

# Count markets moving up/down on that date
cross["markets_up_count"] = (
    cross
    .assign(
        market_up=(
            cross["modal_price"]
            > cross["prev_price"]
        )
    )
    .groupby(["commodity_name", "report_date"])["market_up"]
    .transform("sum")
)

cross["markets_down_count"] = (
    cross
    .assign(
        market_down=(
            cross["modal_price"]
            < cross["prev_price"]
        )
    )
    .groupby(["commodity_name", "report_date"])["market_down"]
    .transform("sum")
)

cross["pct_markets_up"] = (
    cross["markets_up_count"]
    / cross["same_day_market_count"]
)

cross["pct_markets_down"] = (
    cross["markets_down_count"]
    / cross["same_day_market_count"]
)

# Keep only the features we want
CROSS_FEATURES = [
    "same_day_market_count",
    "cross_market_mean",
    "same_day_price_median_all",
    "price_vs_market_median",
    "price_vs_other_market_mean",
    "pct_markets_up",
    "pct_markets_down"
]

# Merge back into df_daily
df_daily = df_daily.merge(
    cross[
        [
            "market_name",
            "commodity_name",
            "report_date"
        ] + CROSS_FEATURES
    ],
    on=[
        "market_name",
        "commodity_name",
        "report_date"
    ],
    how="left"
)

print("Cross-market features added.")

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "modal_price"
        ] + CROSS_FEATURES
    ].head(20)
)

Cross-market features added.
     market_name commodity_name report_date  modal_price  \
0   APMC Aatpadi    Pomegranate  2021-01-14      13500.0
1   APMC Aatpadi    Pomegranate  2021-01-15      13500.0
2   APMC Aatpadi    Pomegranate  2021-01-17      15000.0
3   APMC Aatpadi    Pomegranate  2021-01-18      12000.0
4   APMC Aatpadi    Pomegranate  2021-01-19      12500.0
5   APMC Aatpadi    Pomegranate  2021-01-20      13500.0
6   APMC Aatpadi    Pomegranate  2021-01-21      13500.0
7   APMC Aatpadi    Pomegranate  2021-01-22      10500.0
8   APMC Aatpadi    Pomegranate  2021-01-24      12500.0
9   APMC Aatpadi    Pomegranate  2021-01-26      15000.0
10  APMC Aatpadi    Pomegranate  2021-02-04      18500.0
11  APMC Aatpadi    Pomegranate  2021-02-12      18500.0
12  APMC Aatpadi    Pomegranate  2021-02-15      18500.0
13  APMC Aatpadi    Pomegranate  2021-02-19      16500.0
14  APMC Aatpadi    Pomegranate  2021-02-22      18500.0
15  APMC Aatpadi    Pomegranate  2021-02-23      13500.0
16  APMC Aatpadi    Pomegranate  2021-02-24      13500.0
17  APMC Aatpadi    Pomegranate  2021-02-25      11500.0
18  APMC Aatpadi    Pomegranate  2021-02-26      13500.0
19  APMC Aatpadi    Pomegranate  2021-02-28      13500.0

    same_day_market_count  cross_market_mean  same_day_price_median_all  \
0                       4        9416.666667                    11125.0
1                       4       11200.000000                    11750.0
2                       1                NaN                    15000.0
3                       8        9000.000000                     9500.0
4                       6        8650.000000                     9250.0
5                       9        9356.250000                     9500.0
6                       5        8750.000000                    10000.0
7                       5        9437.500000                    10500.0
8                       1                NaN                    12500.0
9                       2       10000.000000                    12500.0
10                      6        7660.000000                     9900.0
11                      6        9240.000000                    11000.0
12                      8        7828.571429                     7750.0
13                      2       12750.000000                    14625.0
14                      6        8840.000000                    10250.0
15                      6        8750.000000                     9750.0
16                      8        8264.285714                     9250.0
17                      7        8283.333333                     9500.0
18                      7        8791.666667                     9500.0
19                      3        5250.000000                     6500.0

    price_vs_market_median  price_vs_other_market_mean  pct_markets_up  \
0                 1.213483                    1.433628        0.000000
1                 1.148936                    1.205357        0.500000
2                 1.000000                         NaN        1.000000
3                 1.263158                    1.333333        0.375000
4                 1.351351                    1.445087        0.333333
5                 1.421053                    1.442886        0.555556
6                 1.350000                    1.542857        0.200000
7                 1.000000                    1.112583        0.400000
8                 1.000000                         NaN        1.000000
9                 1.200000                    1.500000        1.000000
10                1.868687                    2.415144        0.333333
11                1.681818                    2.002165        0.500000
12                2.387097                    2.363139        0.250000
13                1.128205                    1.294118        0.000000
14                1.804878                    2.092760        0.500000
15                1.384615                    1.542857        0.333333
16                1.459459                    1.633535        0.500000
17                1.210526                    1.388330        0.571429
18                1.421053                    1.535545        0.285714
19                2.076923                    2.571429        0.000000

    pct_markets_down
0           0.000000
1           0.000000
2           0.000000
3           0.625000
4           0.166667
5           0.111111
6           0.600000
7           0.400000
8           0.000000
9           0.000000
10          0.500000
11          0.333333
12          0.125000
13          1.000000
14          0.500000
15          0.666667
16          0.250000
17          0.428571
18          0.428571
19          0.666667

In [67]:
print("Cross-market feature summary:\n")

print(
    df_daily[CROSS_FEATURES].describe().T
)

print("\nMissing values:\n")

print(
    df_daily[CROSS_FEATURES].isna().sum()
)

Cross-market feature summary:

                                count         mean          std       min  \
same_day_market_count       1615735.0    26.468680    20.586096  1.000000
cross_market_mean           1567350.0  3430.870677  2559.251335  1.000000
same_day_price_median_all   1615735.0  3819.599756  7168.470458  1.000000
price_vs_market_median      1615735.0     1.487624     9.069557  0.000114
price_vs_other_market_mean  1567350.0     1.127343     5.088812  0.000115
pct_markets_up              1615735.0     0.365293     0.170974  0.000000
pct_markets_down            1615735.0     0.363597     0.169252  0.000000

                                    25%          50%          75%  \
same_day_market_count         11.000000    22.000000    35.000000
cross_market_mean           1707.200000  2633.333333  4530.258590
same_day_price_median_all   1600.000000  2582.500000  4600.000000
price_vs_market_median         0.900000     1.000000     1.111111
price_vs_other_market_mean     0.837185     0.984010     1.111804
pct_markets_up                 0.266667     0.368421     0.466667
pct_markets_down               0.266667     0.366667     0.466667

                                      max
same_day_market_count          104.000000
cross_market_mean            55000.000000
same_day_price_median_all   350000.000000
price_vs_market_median         714.285714
price_vs_other_market_mean    2750.000000
pct_markets_up                   1.000000
pct_markets_down                 1.000000

Missing values:

same_day_market_count             0
cross_market_mean             48385
same_day_price_median_all         0
price_vs_market_median            0
price_vs_other_market_mean    48385
pct_markets_up                    0
pct_markets_down                  0
dtype: int64

In [68]:
print("Rows with only one market reporting:")
print(
    (df_daily["same_day_market_count"] == 1).sum()
)

print(
    "Percentage:",
    (
        df_daily["same_day_market_count"] == 1
    ).mean() * 100
)

print("\nPrice ratio percentiles:")

print(
    df_daily[
        [
            "price_vs_market_median",
            "price_vs_other_market_mean"
        ]
    ].quantile(
        [0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

Rows with only one market reporting:
48385
Percentage: 2.9946123590811613

Price ratio percentiles:
      price_vs_market_median  price_vs_other_market_mean
0.01                0.014545                    0.008822
0.05                0.569231                    0.486056
0.25                0.900000                    0.837185
0.50                1.000000                    0.984010
0.75                1.111111                    1.111804
0.95                1.666667                    1.660979
0.99                3.166667                    2.830234

In [69]:
# Recalculate same-day market movement using OTHER markets only

cross_move = df_daily[
    [
        "market_name",
        "commodity_name",
        "report_date",
        "modal_price"
    ]
].copy()

# Previous reported price for each market + commodity
cross_move["prev_price"] = (
    cross_move
    .groupby(["market_name", "commodity_name"])["modal_price"]
    .shift(1)
)

# Current market movement
cross_move["current_up"] = (
    cross_move["modal_price"]
    > cross_move["prev_price"]
)

cross_move["current_down"] = (
    cross_move["modal_price"]
    < cross_move["prev_price"]
)

# Total markets moving up/down for commodity + date
total_up = (
    cross_move
    .groupby(["commodity_name", "report_date"])["current_up"]
    .transform("sum")
)

total_down = (
    cross_move
    .groupby(["commodity_name", "report_date"])["current_down"]
    .transform("sum")
)

market_count = (
    cross_move
    .groupby(["commodity_name", "report_date"])["market_name"]
    .transform("nunique")
)

# Exclude the current market
other_market_count = market_count - 1

other_up = total_up - cross_move["current_up"].astype(int)
other_down = total_down - cross_move["current_down"].astype(int)

df_daily["pct_other_markets_up"] = np.where(
    other_market_count > 0,
    other_up / other_market_count,
    np.nan
)

df_daily["pct_other_markets_down"] = np.where(
    other_market_count > 0,
    other_down / other_market_count,
    np.nan
)

print(
    df_daily[
        [
            "market_name",
            "commodity_name",
            "report_date",
            "same_day_market_count",
            "pct_other_markets_up",
            "pct_other_markets_down"
        ]
    ].head(20)
)

print("\nMissing values:")
print(
    df_daily[
        [
            "pct_other_markets_up",
            "pct_other_markets_down"
        ]
    ].isna().sum()
)

     market_name commodity_name report_date  same_day_market_count  \
0   APMC Aatpadi    Pomegranate  2021-01-14                      4
1   APMC Aatpadi    Pomegranate  2021-01-15                      4
2   APMC Aatpadi    Pomegranate  2021-01-17                      1
3   APMC Aatpadi    Pomegranate  2021-01-18                      8
4   APMC Aatpadi    Pomegranate  2021-01-19                      6
5   APMC Aatpadi    Pomegranate  2021-01-20                      9
6   APMC Aatpadi    Pomegranate  2021-01-21                      5
7   APMC Aatpadi    Pomegranate  2021-01-22                      5
8   APMC Aatpadi    Pomegranate  2021-01-24                      1
9   APMC Aatpadi    Pomegranate  2021-01-26                      2
10  APMC Aatpadi    Pomegranate  2021-02-04                      6
11  APMC Aatpadi    Pomegranate  2021-02-12                      6
12  APMC Aatpadi    Pomegranate  2021-02-15                      8
13  APMC Aatpadi    Pomegranate  2021-02-19                      2
14  APMC Aatpadi    Pomegranate  2021-02-22                      6
15  APMC Aatpadi    Pomegranate  2021-02-23                      6
16  APMC Aatpadi    Pomegranate  2021-02-24                      8
17  APMC Aatpadi    Pomegranate  2021-02-25                      7
18  APMC Aatpadi    Pomegranate  2021-02-26                      7
19  APMC Aatpadi    Pomegranate  2021-02-28                      3

    pct_other_markets_up  pct_other_markets_down
0               0.000000                0.000000
1               0.666667                0.000000
2                    NaN                     NaN
3               0.428571                0.571429
4               0.200000                0.200000
5               0.500000                0.125000
6               0.250000                0.750000
7               0.500000                0.250000
8                    NaN                     NaN
9               1.000000                0.000000
10              0.200000                0.600000
11              0.600000                0.400000
12              0.285714                0.142857
13              0.000000                1.000000
14              0.400000                0.600000
15              0.400000                0.600000
16              0.571429                0.285714
17              0.666667                0.333333
18              0.166667                0.500000
19              0.000000                1.000000

Missing values:
pct_other_markets_up      48385
pct_other_markets_down    48385
dtype: int64

In [70]:
CROSS_FEATURES_FINAL = [
    "same_day_market_count",
    "cross_market_mean",
    "same_day_price_median_all",
    "price_vs_market_median",
    "price_vs_other_market_mean",
    "pct_other_markets_up",
    "pct_other_markets_down"
]

print("Cross-market features:")
for feature in CROSS_FEATURES_FINAL:
    print("-", feature)

print("\nNumber of cross-market features:", len(CROSS_FEATURES_FINAL))

Cross-market features:
- same_day_market_count
- cross_market_mean
- same_day_price_median_all
- price_vs_market_median
- price_vs_other_market_mean
- pct_other_markets_up
- pct_other_markets_down

Number of cross-market features: 7

In [71]:
FEATURES_CROSS = [
    "market_name",
    "commodity_name",

    "modal_price",
    "min_price",
    "max_price",
    "arrivals",

    "days_since_last_report",

    "price_lag_1",
    "price_lag_2",
    "price_lag_3",
    "price_lag_7",

    "price_roll_mean_7",
    "price_roll_std_7",
    "price_roll_mean_30",

    # Cross-market information
    "same_day_market_count",
    "cross_market_mean",
    "same_day_price_median_all",
    "price_vs_market_median",
    "price_vs_other_market_mean",
    "pct_other_markets_up",
    "pct_other_markets_down",

    "year",
    "month",
    "day_of_week",
    "week_of_year"
]

CATEGORICAL = [
    "market_name",
    "commodity_name"
]

print("Total features:", len(FEATURES_CROSS))

for feature in FEATURES_CROSS:
    print("-", feature)

Total features: 25
- market_name
- commodity_name
- modal_price
- min_price
- max_price
- arrivals
- days_since_last_report
- price_lag_1
- price_lag_2
- price_lag_3
- price_lag_7
- price_roll_mean_7
- price_roll_std_7
- price_roll_mean_30
- same_day_market_count
- cross_market_mean
- same_day_price_median_all
- price_vs_market_median
- price_vs_other_market_mean
- pct_other_markets_up
- pct_other_markets_down
- year
- month
- day_of_week
- week_of_year

In [72]:
# Rebuild modeling dataset after adding cross-market features

df_model = df_daily[
    df_daily["horizon_days"].between(7, 14)
].copy()

df_model = df_model.dropna(
    subset=["target_price"]
).copy()

# Recreate classification target
df_model["pct_change_7"] = (
    (df_model["target_price"] - df_model["modal_price"])
    / df_model["modal_price"]
)

df_model["direction"] = pd.cut(
    df_model["pct_change_7"],
    bins=[-np.inf, -0.02, 0.02, np.inf],
    labels=["down", "flat", "up"]
)

print("Final modeling rows:", len(df_model))

print("\nMissing cross-market features:")
print(
    df_model[CROSS_FEATURES_FINAL].isna().sum()
)

print("\nDirection distribution:")
print(
    df_model["direction"].value_counts()
)

Final modeling rows: 1243583

Missing cross-market features:
same_day_market_count             0
cross_market_mean             39151
same_day_price_median_all         0
price_vs_market_median            0
price_vs_other_market_mean    39151
pct_other_markets_up          39151
pct_other_markets_down        39151
dtype: int64

Direction distribution:
direction
up      451224
down    440096
flat    352263
Name: count, dtype: int64

In [73]:
split_train_end = pd.Timestamp("2025-06-30")
split_val_end = pd.Timestamp("2025-12-31")

train = df_model[
    df_model["report_date"] <= split_train_end
].copy()

val = df_model[
    (df_model["report_date"] > split_train_end) &
    (df_model["report_date"] <= split_val_end)
].copy()

test = df_model[
    df_model["report_date"] > split_val_end
].copy()

print("Train shape:", train.shape)
print("Validation shape:", val.shape)
print("Test shape:", test.shape)

print("\nDate ranges:")

print(
    "Train:",
    train["report_date"].min(),
    "→",
    train["report_date"].max()
)

print(
    "Validation:",
    val["report_date"].min(),
    "→",
    val["report_date"].max()
)

print(
    "Test:",
    test["report_date"].min(),
    "→",
    test["report_date"].max()
)

Train shape: (948244, 39)
Validation shape: (115363, 39)
Test shape: (179976, 39)

Date ranges:
Train: 2021-01-01 00:00:00 → 2025-06-30 00:00:00
Validation: 2025-07-01 00:00:00 → 2025-12-31 00:00:00
Test: 2026-01-01 00:00:00 → 2026-09-06 00:00:00

In [74]:
# Prepare categorical columns
for col in CATEGORICAL:
    categories = df_model[col].astype("category").cat.categories

    train[col] = pd.Categorical(
        train[col],
        categories=categories
    )

    val[col] = pd.Categorical(
        val[col],
        categories=categories
    )

    test[col] = pd.Categorical(
        test[col],
        categories=categories
    )

# Regression datasets
X_train_cross = train[FEATURES_CROSS]
X_val_cross = val[FEATURES_CROSS]
X_test_cross = test[FEATURES_CROSS]

y_train_cross = train["target_price"]
y_val_cross = val["target_price"]
y_test_cross = test["target_price"]

print("X_train:", X_train_cross.shape)
print("X_val:", X_val_cross.shape)
print("X_test:", X_test_cross.shape)

print("\ny_train:", y_train_cross.shape)
print("y_val:", y_val_cross.shape)
print("y_test:", y_test_cross.shape)

print("\nMissing cross-market features in train:")
print(
    X_train_cross[CROSS_FEATURES_FINAL].isna().sum()
)

X_train: (948244, 25)
X_val: (115363, 25)
X_test: (179976, 25)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

Missing cross-market features in train:
same_day_market_count             0
cross_market_mean             30613
same_day_price_median_all         0
price_vs_market_median            0
price_vs_other_market_mean    30613
pct_other_markets_up          30613
pct_other_markets_down        30613
dtype: int64

In [75]:
from lightgbm import LGBMRegressor, early_stopping, log_evaluation

regressor_cross = LGBMRegressor(
    objective="regression",
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

regressor_cross.fit(
    X_train_cross,
    np.log1p(y_train_cross),

    eval_set=[
        (X_val_cross, np.log1p(y_val_cross))
    ],

    eval_metric="l2",

    categorical_feature=CATEGORICAL,

    callbacks=[
        early_stopping(100),
        log_evaluation(100)
    ]
)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.092660 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4949
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 25
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Start training from score 7.723530
Training until validation scores don't improve for 100 rounds
[100]	valid_0's l2: 0.0551983
[200]	valid_0's l2: 0.0511105
[300]	valid_0's l2: 0.0506332
[400]	valid_0's l2: 0.050504
[500]	valid_0's l2: 0.0503994
[600]	valid_0's l2: 0.0503078
[700]	valid_0's l2: 0.0502672
Early stopping, best iteration is:
[662]	valid_0's l2: 0.0502567

LGBMRegressor(colsample_bytree=0.8, learning_rate=0.03, min_data_in_leaf=100,
              n_estimators=3000, n_jobs=-1, num_leaves=63,
              objective='regression', random_state=42, subsample=0.8)

In [76]:
pred_log_cross = regressor_cross.predict(
    X_test_cross
)

pred_price_cross = np.expm1(
    pred_log_cross
)

pred_price_cross = np.maximum(
    pred_price_cross,
    0
)

print(
    "Number of predictions:",
    len(pred_price_cross)
)

print("\nFirst 10 predictions:")
print(pred_price_cross[:10])

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
Number of predictions: 179976

First 10 predictions:
[8717.47374736 9132.2179412  8492.74995748 8664.43898526 9114.04631634
 9441.51697064 9536.13402453 9586.3491402  9729.64397002 9583.564103  ]

In [77]:
# Evaluate cross-market LightGBM on the untouched test set

mae_cross = mean_absolute_error(
    y_test_cross,
    pred_price_cross
)

rmse_cross = np.sqrt(
    mean_squared_error(
        y_test_cross,
        pred_price_cross
    )
)

smape_cross = (
    100
    * np.mean(
        2 * np.abs(pred_price_cross - y_test_cross)
        /
        (
            np.abs(y_test_cross)
            + np.abs(pred_price_cross)
            + 1e-8
        )
    )
)

print("CROSS-MARKET LIGHTGBM")
print(f"MAE   : ₹{mae_cross:,.2f}")
print(f"RMSE  : ₹{rmse_cross:,.2f}")
print(f"sMAPE : {smape_cross:.2f}%")

print("\nNAIVE BASELINE")
print(f"MAE   : ₹{naive_mae:,.2f}")
print(f"RMSE  : ₹{naive_rmse:,.2f}")
print(f"sMAPE : {naive_smape:.2f}%")

print("\nBEST PREVIOUS LOG MODEL")
print(f"MAE   : ₹{mae_v3:,.2f}")
print(f"RMSE  : ₹{rmse_v3:,.2f}")
print(f"sMAPE : {smape_v3:.2f}%")

CROSS-MARKET LIGHTGBM
MAE   : ₹430.94
RMSE  : ₹1,016.20
sMAPE : 12.84%

NAIVE BASELINE
MAE   : ₹441.84
RMSE  : ₹917.38
sMAPE : 13.90%

BEST PREVIOUS LOG MODEL
MAE   : ₹436.93
RMSE  : ₹1,097.29
sMAPE : 12.92%

In [78]:
reg_test_cross = test[
    [
        "commodity_name",
        "target_price",
        "modal_price"
    ]
].copy()

reg_test_cross["predicted_price"] = pred_price_cross

reg_test_cross["abs_error_model"] = (
    reg_test_cross["target_price"]
    - reg_test_cross["predicted_price"]
).abs()

reg_test_cross["abs_error_naive"] = (
    reg_test_cross["target_price"]
    - reg_test_cross["modal_price"]
).abs()

crop_regression_cross = (
    reg_test_cross
    .groupby("commodity_name", observed=True)
    .agg(
        test_rows=("target_price", "size"),
        model_mae=("abs_error_model", "mean"),
        naive_mae=("abs_error_naive", "mean")
    )
    .reset_index()
)

crop_regression_cross["mae_lift_pct"] = (
    (
        crop_regression_cross["naive_mae"]
        - crop_regression_cross["model_mae"]
    )
    / crop_regression_cross["naive_mae"]
) * 100

priority_regression_cross = (
    crop_regression_cross[
        crop_regression_cross["commodity_name"].isin(
            priority_crops
        )
    ]
    .sort_values(
        "mae_lift_pct",
        ascending=False
    )
)

print(
    priority_regression_cross.to_string(index=False)
)

           commodity_name  test_rows  model_mae  naive_mae  mae_lift_pct
                   Tomato       6541 308.302304 357.886256     13.854668
                    Wheat       9105  83.547322  92.921582     10.088355
                    Onion       8481 216.775023 236.125044      8.194820
Red gram/Arhar/Tur(whole)       6769 305.678042 321.653494      4.966665
                 Soyabean       6851 328.202327 344.318786      4.680679
                   Cotton       1420 227.188532 204.342444    -11.180295

In [80]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(["down", "flat", "up"])

train["direction_encoded"] = label_encoder.transform(
    train["direction"]
)

val["direction_encoded"] = label_encoder.transform(
    val["direction"]
)

test["direction_encoded"] = label_encoder.transform(
    test["direction"]
)

print("Class mapping:")
print(
    dict(
        zip(
            label_encoder.classes_,
            range(len(label_encoder.classes_))
        )
    )
)

print("\nTrain class counts:")
print(train["direction"].value_counts())

Class mapping:
{np.str_('down'): 0, np.str_('flat'): 1, np.str_('up'): 2}

Train class counts:
direction
up      344926
down    335103
flat    268215
Name: count, dtype: int64

In [81]:
X_train_cls_cross = train[FEATURES_CROSS]
X_val_cls_cross = val[FEATURES_CROSS]
X_test_cls_cross = test[FEATURES_CROSS]

y_train_cls_cross = train["direction_encoded"]
y_val_cls_cross = val["direction_encoded"]
y_test_cls_cross = test["direction_encoded"]

print("X_train:", X_train_cls_cross.shape)
print("X_val:", X_val_cls_cross.shape)
print("X_test:", X_test_cls_cross.shape)

print("\ny_train:", y_train_cls_cross.shape)
print("y_val:", y_val_cls_cross.shape)
print("y_test:", y_test_cls_cross.shape)

X_train: (948244, 25)
X_val: (115363, 25)
X_test: (179976, 25)

y_train: (948244,)
y_val: (115363,)
y_test: (179976,)

In [84]:
import lightgbm as lgb
from lightgbm import LGBMClassifier

classifier_cross = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=3000,
    learning_rate=0.05,
    num_leaves=63,
    min_data_in_leaf=200,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

classifier_cross.fit(
    X_train_cls_cross,
    y_train_cls_cross,
    categorical_feature=["market_name", "commodity_name"],
    eval_set=[(X_val_cls_cross, y_val_cls_cross)],
    callbacks=[
        lgb.early_stopping(100),
        lgb.log_evaluation(100)
    ]
)

print("Best iteration:", classifier_cross.best_iteration_)

c:\Users\hp\anaconda3\envs\myenv\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.112647 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4949
[LightGBM] [Info] Number of data points in the train set: 948244, number of used features: 25
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Info] Start training from score -1.040174
[LightGBM] [Info] Start training from score -1.262823
[LightGBM] [Info] Start training from score -1.011282
Training until validation scores don't improve for 100 rounds
[100]	valid_0's multi_logloss: 0.923775
[200]	valid_0's multi_logloss: 0.912826
[300]	valid_0's multi_logloss: 0.910369
[400]	valid_0's multi_logloss: 0.910195
[500]	valid_0's multi_logloss: 0.910444
Early stopping, best iteration is:
[457]	valid_0's multi_logloss: 0.90988
Best iteration: 457

In [85]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

y_pred_cross = classifier_cross.predict(X_test_cls_cross)

print("Overall Accuracy:")
print(accuracy_score(y_test_cls_cross, y_pred_cross))

print("\nClassification Report:")
print(
    classification_report(
        y_test_cls_cross,
        y_pred_cross,
        target_names=label_encoder.classes_,
        digits=4
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls_cross, y_pred_cross))

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
Overall Accuracy:
0.5564408587811708

Classification Report:
              precision    recall  f1-score   support

        down     0.5533    0.6013    0.5763     61894
        flat     0.5660    0.4445    0.4980     51835
          up     0.5540    0.6021    0.5770     66247

    accuracy                         0.5564    179976
   macro avg     0.5578    0.5493    0.5504    179976
weighted avg     0.5572    0.5564    0.5540    179976


Confusion Matrix:
[[37217  7381 17296]
 [13974 23043 14818]
 [16074 10287 39886]]

In [86]:
priority_crops = [
    "Onion",
    "Tomato",
    "Soyabean",
    "Wheat",
    "Red gram/Arhar/Tur(whole)",
    "Cotton"
]

crop_results_cross = []

for crop in priority_crops:
    mask = test["commodity_name"].eq(crop)

    y_true_crop = y_test_cls_cross[mask]
    y_pred_crop = y_pred_cross[mask]

    # UP/DOWN only
    non_flat = y_true_crop != 1

    if non_flat.sum() > 0:
        up_down_acc = accuracy_score(
            y_true_crop[non_flat],
            y_pred_crop[non_flat]
        )
    else:
        up_down_acc = np.nan

    crop_results_cross.append({
        "commodity": crop,
        "n_test": mask.sum(),
        "up_down_accuracy": up_down_acc
    })

crop_results_cross = pd.DataFrame(crop_results_cross)

print(crop_results_cross)

                   commodity  n_test  up_down_accuracy
0                      Onion    8481          0.688562
1                     Tomato    6541          0.692204
2                   Soyabean    6851          0.358509
3                      Wheat    9105          0.432377
4  Red gram/Arhar/Tur(whole)    6769          0.339105
5                     Cotton    1420          0.032609

In [87]:
distribution_rows = []

for crop in priority_crops:
    mask = test["commodity_name"].eq(crop)

    actual_counts = pd.Series(y_test_cls_cross[mask]).value_counts(
        normalize=True
    )
    predicted_counts = pd.Series(y_pred_cross[mask]).value_counts(
        normalize=True
    )

    distribution_rows.append({
        "commodity": crop,

        "actual_down": actual_counts.get(0, 0),
        "actual_flat": actual_counts.get(1, 0),
        "actual_up": actual_counts.get(2, 0),

        "pred_down": predicted_counts.get(0, 0),
        "pred_flat": predicted_counts.get(1, 0),
        "pred_up": predicted_counts.get(2, 0),
    })

crop_distribution_cross = pd.DataFrame(distribution_rows)

print(crop_distribution_cross.round(4))

                   commodity  actual_down  actual_flat  actual_up  pred_down  \
0                      Onion       0.3273       0.1671     0.5056     0.4415
1                     Tomato       0.4175       0.2038     0.3787     0.4415
2                   Soyabean       0.3357       0.2521     0.4122     0.4376
3                      Wheat       0.2499       0.4145     0.3356     0.2160
4  Red gram/Arhar/Tur(whole)       0.2715       0.4027     0.3257     0.3522
5                     Cotton       0.1796       0.5465     0.2739     0.0169

   pred_flat  pred_up
0     0.0283   0.5302
1     0.0301   0.5284
2     0.4426   0.1198
3     0.5430   0.2410
4     0.5181   0.1297
5     0.9697   0.0134

In [88]:
feature_importance_cross = (
    pd.DataFrame({
        "feature": FEATURES_CROSS,
        "importance": classifier_cross.feature_importances_
    })
    .sort_values("importance", ascending=False)
)

print(feature_importance_cross.to_string(index=False))

                   feature  importance
               market_name       24147
            commodity_name       15611
              week_of_year        7638
               modal_price        6073
                      year        3066
          price_roll_std_7        2240
        price_roll_mean_30        2117
         cross_market_mean        2025
         price_roll_mean_7        1954
price_vs_other_market_mean        1883
    price_vs_market_median        1876
 same_day_price_median_all        1762
                     month        1738
               price_lag_1        1718
                 max_price        1686
     same_day_market_count        1538
                 min_price        1508
                  arrivals        1279
               price_lag_2        1220
               price_lag_7         930
               price_lag_3         907
      pct_other_markets_up         890
    pct_other_markets_down         834
               day_of_week         231
    days_since_last_report         131

In [89]:
prob_cross = classifier_cross.predict_proba(X_test_cls_cross)

confidence_cross = prob_cross.max(axis=1)
predicted_class_cross = prob_cross.argmax(axis=1)

confidence_summary = pd.Series(confidence_cross).describe(
    percentiles=[0.50, 0.60, 0.70, 0.80, 0.90]
)

print(confidence_summary)

print("\nConfidence >= 0.60:")
print((confidence_cross >= 0.60).mean())

print("\nConfidence >= 0.70:")
print((confidence_cross >= 0.70).mean())

print("\nConfidence >= 0.80:")
print((confidence_cross >= 0.80).mean())

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
count    179976.000000
mean          0.579950
std           0.138683
min           0.333745
50%           0.555386
60%           0.596704
70%           0.644791
80%           0.704425
90%           0.784563
max           0.992276
dtype: float64

Confidence >= 0.60:
0.3926912477219185

Confidence >= 0.70:
0.20669422589678624

Confidence >= 0.80:
0.08460016891141041

In [91]:
decision_correct = (
    (
        (issued["recommendation"] == "HOLD") &
        (issued["direction"] == "up")
    )
    |
    (
        (issued["recommendation"] == "SELL") &
        (issued["direction"] == "down")
    )
)

print("Overall decision accuracy:")
print(f"{decision_correct.mean():.2%}")

print("\nHOLD accuracy:")
hold_mask = issued["recommendation"] == "HOLD"
print(f"{decision_correct[hold_mask].mean():.2%}")

print("\nSELL accuracy:")
sell_mask = issued["recommendation"] == "SELL"
print(f"{decision_correct[sell_mask].mean():.2%}")

print("\nNumber of correct decisions:")
print(decision_correct.sum())

print("\nNumber of issued decisions:")
print(len(issued))

Overall decision accuracy:
68.69%

HOLD accuracy:
68.17%

SELL accuracy:
69.30%

Number of correct decisions:
37374

Number of issued decisions:
54412

In [92]:
crop_decision_results = []

for crop in priority_crops:
    crop_issued = issued[
        issued["commodity_name"].eq(crop)
    ].copy()

    if len(crop_issued) == 0:
        continue

    crop_correct = (
        (
            (crop_issued["recommendation"] == "HOLD") &
            (crop_issued["direction"] == "up")
        )
        |
        (
            (crop_issued["recommendation"] == "SELL") &
            (crop_issued["direction"] == "down")
        )
    )

    crop_decision_results.append({
        "commodity": crop,
        "issued_decisions": len(crop_issued),
        "decision_coverage": len(crop_issued) / (test["commodity_name"] == crop).sum(),
        "decision_accuracy": crop_correct.mean()
    })

crop_decision_results = pd.DataFrame(crop_decision_results)

print(crop_decision_results.to_string(index=False))

                commodity  issued_decisions  decision_coverage  decision_accuracy
                    Onion              3357           0.395826           0.721478
                   Tomato              2403           0.367375           0.715772
                 Soyabean              1082           0.157933           0.556377
                    Wheat              1165           0.127952           0.761373
Red gram/Arhar/Tur(whole)               679           0.100310           0.583211
                   Cotton                 9           0.006338           0.222222

In [ ]:
results_cross["predicted_price"] = regressor_cross.predict(
    test[FEATURES_CROSS]
)

results_cross["predicted_pct_change"] = (
    (results_cross["predicted_price"] - results_cross["modal_price"])
    / results_cross["modal_price"]
) * 100

results_cross["regression_direction"] = np.select(
    [
        results_cross["predicted_pct_change"] < -2,
        results_cross["predicted_pct_change"] > 2
    ],
    [
        "down",
        "up"
    ],
    default="flat"
)

results_cross["direction_agreement"] = (
    results_cross["predicted_direction"] ==
    results_cross["regression_direction"]
)

print("Direction agreement:")
print(results_cross["direction_agreement"].value_counts())

print(
    f"\nAgreement rate: "
    f"{results_cross['direction_agreement'].mean():.2%}"
)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
Direction agreement:
direction_agreement
False    112711
True      67265
Name: count, dtype: int64

Agreement rate: 37.37%

In [94]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

y_pred_reg_cross = results_cross["predicted_price"]
y_true_reg_cross = results_cross["target_price"]

mae_cross = mean_absolute_error(y_true_reg_cross, y_pred_reg_cross)
rmse_cross = np.sqrt(
    mean_squared_error(y_true_reg_cross, y_pred_reg_cross)
)

smape_cross = (
    100
    * np.mean(
        2 * np.abs(y_pred_reg_cross - y_true_reg_cross)
        / (
            np.abs(y_true_reg_cross)
            + np.abs(y_pred_reg_cross)
            + 1e-8
        )
    )
)

print(f"MAE  : ₹{mae_cross:,.2f}")
print(f"RMSE : ₹{rmse_cross:,.2f}")
print(f"sMAPE: {smape_cross:.2f}%")

MAE  : ₹4,142.43
RMSE : ₹9,398.40
sMAPE: 196.77%

In [95]:
# Convert log-price prediction back to actual price
pred_log_cross = regressor_cross.predict(
    test[FEATURES_CROSS]
)

results_cross["predicted_price"] = np.expm1(pred_log_cross)

results_cross["predicted_pct_change"] = (
    (results_cross["predicted_price"] - results_cross["modal_price"])
    / results_cross["modal_price"]
) * 100

results_cross["regression_direction"] = np.select(
    [
        results_cross["predicted_pct_change"] < -2,
        results_cross["predicted_pct_change"] > 2
    ],
    [
        "down",
        "up"
    ],
    default="flat"
)

print(results_cross[
    ["modal_price", "target_price", "predicted_price"]
].head())

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
     modal_price  target_price  predicted_price
792       8500.0        7500.0      8717.473747
793       9000.0        9200.0      9132.217941
794       7200.0        7000.0      8492.749957
802       8000.0        9000.0      8664.438985
803       8700.0        8700.0      9114.046316

In [96]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

y_true_reg_cross = results_cross["target_price"]
y_pred_reg_cross = results_cross["predicted_price"]

mae_cross = mean_absolute_error(
    y_true_reg_cross,
    y_pred_reg_cross
)

rmse_cross = np.sqrt(
    mean_squared_error(
        y_true_reg_cross,
        y_pred_reg_cross
    )
)

smape_cross = (
    100
    * np.mean(
        2 * np.abs(y_pred_reg_cross - y_true_reg_cross)
        / (
            np.abs(y_true_reg_cross)
            + np.abs(y_pred_reg_cross)
            + 1e-8
        )
    )
)

print(f"MAE  : ₹{mae_cross:,.2f}")
print(f"RMSE : ₹{rmse_cross:,.2f}")
print(f"sMAPE: {smape_cross:.2f}%")

MAE  : ₹430.94
RMSE : ₹1,016.20
sMAPE: 12.84%

In [97]:
naive_pred = test["modal_price"]

naive_mae = mean_absolute_error(
    test["target_price"],
    naive_pred
)

naive_rmse = np.sqrt(
    mean_squared_error(
        test["target_price"],
        naive_pred
    )
)

naive_smape = (
    100
    * np.mean(
        2 * np.abs(naive_pred - test["target_price"])
        / (
            np.abs(naive_pred)
            + np.abs(test["target_price"])
            + 1e-8
        )
    )
)

print("Cross-market model:")
print(f"MAE  : ₹{mae_cross:,.2f}")
print(f"RMSE : ₹{rmse_cross:,.2f}")
print(f"sMAPE: {smape_cross:.2f}%")

print("\nNaive current-price baseline:")
print(f"MAE  : ₹{naive_mae:,.2f}")
print(f"RMSE : ₹{naive_rmse:,.2f}")
print(f"sMAPE: {naive_smape:.2f}%")

Cross-market model:
MAE  : ₹430.94
RMSE : ₹1,016.20
sMAPE: 12.84%

Naive current-price baseline:
MAE  : ₹441.84
RMSE : ₹917.38
sMAPE: 13.90%